// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/prydin/go-fitter/client/activity"
	"github.com/prydin/go-fitter/client/auth"
	"github.com/prydin/go-fitter/client/body_and_weight"
	"github.com/prydin/go-fitter/client/devices"
	"github.com/prydin/go-fitter/client/food_logging"
	"github.com/prydin/go-fitter/client/friends"
	"github.com/prydin/go-fitter/client/sleep"
	"github.com/prydin/go-fitter/client/subscriptions"
	"github.com/prydin/go-fitter/client/time_series"
	"github.com/prydin/go-fitter/client/user"
)

// Default fitbit web HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.fitbit.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new fitbit web HTTP client.
func NewHTTPClient(formats strfmt.Registry) *FitbitWeb {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new fitbit web HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *FitbitWeb {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new fitbit web client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *FitbitWeb {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(FitbitWeb)
	cli.Transport = transport

	cli.Activity = activity.New(transport, formats)

	cli.Auth = auth.New(transport, formats)

	cli.BodyAndWeight = body_and_weight.New(transport, formats)

	cli.Devices = devices.New(transport, formats)

	cli.FoodLogging = food_logging.New(transport, formats)

	cli.Friends = friends.New(transport, formats)

	cli.Sleep = sleep.New(transport, formats)

	cli.Subscriptions = subscriptions.New(transport, formats)

	cli.TimeSeries = time_series.New(transport, formats)

	cli.User = user.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// FitbitWeb is a client for fitbit web
type FitbitWeb struct {
	Activity *activity.Client

	Auth *auth.Client

	BodyAndWeight *body_and_weight.Client

	Devices *devices.Client

	FoodLogging *food_logging.Client

	Friends *friends.Client

	Sleep *sleep.Client

	Subscriptions *subscriptions.Client

	TimeSeries *time_series.Client

	User *user.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *FitbitWeb) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Activity.SetTransport(transport)

	c.Auth.SetTransport(transport)

	c.BodyAndWeight.SetTransport(transport)

	c.Devices.SetTransport(transport)

	c.FoodLogging.SetTransport(transport)

	c.Friends.SetTransport(transport)

	c.Sleep.SetTransport(transport)

	c.Subscriptions.SetTransport(transport)

	c.TimeSeries.SetTransport(transport)

	c.User.SetTransport(transport)

}
