// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAlarmsParams creates a new GetAlarmsParams object
// with the default values initialized.
func NewGetAlarmsParams() *GetAlarmsParams {
	var ()
	return &GetAlarmsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAlarmsParamsWithTimeout creates a new GetAlarmsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAlarmsParamsWithTimeout(timeout time.Duration) *GetAlarmsParams {
	var ()
	return &GetAlarmsParams{

		timeout: timeout,
	}
}

// NewGetAlarmsParamsWithContext creates a new GetAlarmsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAlarmsParamsWithContext(ctx context.Context) *GetAlarmsParams {
	var ()
	return &GetAlarmsParams{

		Context: ctx,
	}
}

// NewGetAlarmsParamsWithHTTPClient creates a new GetAlarmsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAlarmsParamsWithHTTPClient(client *http.Client) *GetAlarmsParams {
	var ()
	return &GetAlarmsParams{
		HTTPClient: client,
	}
}

/*GetAlarmsParams contains all the parameters to send to the API endpoint
for the get alarms operation typically these are written to a http.Request
*/
type GetAlarmsParams struct {

	/*TrackerID
	  The ID of the tracker for which data is returned. The tracker-id value is found via the Get Devices endpoint.

	*/
	TrackerID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get alarms params
func (o *GetAlarmsParams) WithTimeout(timeout time.Duration) *GetAlarmsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get alarms params
func (o *GetAlarmsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get alarms params
func (o *GetAlarmsParams) WithContext(ctx context.Context) *GetAlarmsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get alarms params
func (o *GetAlarmsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get alarms params
func (o *GetAlarmsParams) WithHTTPClient(client *http.Client) *GetAlarmsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get alarms params
func (o *GetAlarmsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTrackerID adds the trackerID to the get alarms params
func (o *GetAlarmsParams) WithTrackerID(trackerID int64) *GetAlarmsParams {
	o.SetTrackerID(trackerID)
	return o
}

// SetTrackerID adds the trackerId to the get alarms params
func (o *GetAlarmsParams) SetTrackerID(trackerID int64) {
	o.TrackerID = trackerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAlarmsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tracker-id
	if err := r.SetPathParam("tracker-id", swag.FormatInt64(o.TrackerID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
