// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetProfileReader is a Reader for the GetProfile structure.
type GetProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewGetProfileCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetProfileConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProfileOK creates a GetProfileOK with default headers values
func NewGetProfileOK() *GetProfileOK {
	return &GetProfileOK{}
}

/*GetProfileOK handles this case with default header values.

A successful request.
*/
type GetProfileOK struct {
}

func (o *GetProfileOK) Error() string {
	return fmt.Sprintf("[GET /1/user/-/profile.json][%d] getProfileOK ", 200)
}

func (o *GetProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProfileCreated creates a GetProfileCreated with default headers values
func NewGetProfileCreated() *GetProfileCreated {
	return &GetProfileCreated{}
}

/*GetProfileCreated handles this case with default header values.

Returned if a new subscription was created in response to your request.
*/
type GetProfileCreated struct {
}

func (o *GetProfileCreated) Error() string {
	return fmt.Sprintf("[GET /1/user/-/profile.json][%d] getProfileCreated ", 201)
}

func (o *GetProfileCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProfileUnauthorized creates a GetProfileUnauthorized with default headers values
func NewGetProfileUnauthorized() *GetProfileUnauthorized {
	return &GetProfileUnauthorized{}
}

/*GetProfileUnauthorized handles this case with default header values.

The request requires user authentication.
*/
type GetProfileUnauthorized struct {
}

func (o *GetProfileUnauthorized) Error() string {
	return fmt.Sprintf("[GET /1/user/-/profile.json][%d] getProfileUnauthorized ", 401)
}

func (o *GetProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProfileConflict creates a GetProfileConflict with default headers values
func NewGetProfileConflict() *GetProfileConflict {
	return &GetProfileConflict{}
}

/*GetProfileConflict handles this case with default header values.

Returned if the given user is already subscribed to this stream using a different subscription ID, OR if the given subscription ID is already used to identify a subscription to a different stream.
*/
type GetProfileConflict struct {
}

func (o *GetProfileConflict) Error() string {
	return fmt.Sprintf("[GET /1/user/-/profile.json][%d] getProfileConflict ", 409)
}

func (o *GetProfileConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
