// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBadgesParams creates a new GetBadgesParams object
// with the default values initialized.
func NewGetBadgesParams() *GetBadgesParams {

	return &GetBadgesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBadgesParamsWithTimeout creates a new GetBadgesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBadgesParamsWithTimeout(timeout time.Duration) *GetBadgesParams {

	return &GetBadgesParams{

		timeout: timeout,
	}
}

// NewGetBadgesParamsWithContext creates a new GetBadgesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBadgesParamsWithContext(ctx context.Context) *GetBadgesParams {

	return &GetBadgesParams{

		Context: ctx,
	}
}

// NewGetBadgesParamsWithHTTPClient creates a new GetBadgesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBadgesParamsWithHTTPClient(client *http.Client) *GetBadgesParams {

	return &GetBadgesParams{
		HTTPClient: client,
	}
}

/*GetBadgesParams contains all the parameters to send to the API endpoint
for the get badges operation typically these are written to a http.Request
*/
type GetBadgesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get badges params
func (o *GetBadgesParams) WithTimeout(timeout time.Duration) *GetBadgesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get badges params
func (o *GetBadgesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get badges params
func (o *GetBadgesParams) WithContext(ctx context.Context) *GetBadgesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get badges params
func (o *GetBadgesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get badges params
func (o *GetBadgesParams) WithHTTPClient(client *http.Client) *GetBadgesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get badges params
func (o *GetBadgesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBadgesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
