// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateProfileReader is a Reader for the UpdateProfile structure.
type UpdateProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewUpdateProfileCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewUpdateProfileConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateProfileOK creates a UpdateProfileOK with default headers values
func NewUpdateProfileOK() *UpdateProfileOK {
	return &UpdateProfileOK{}
}

/*UpdateProfileOK handles this case with default header values.

A successful request.
*/
type UpdateProfileOK struct {
}

func (o *UpdateProfileOK) Error() string {
	return fmt.Sprintf("[POST /1/user/-/profile.json][%d] updateProfileOK ", 200)
}

func (o *UpdateProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateProfileCreated creates a UpdateProfileCreated with default headers values
func NewUpdateProfileCreated() *UpdateProfileCreated {
	return &UpdateProfileCreated{}
}

/*UpdateProfileCreated handles this case with default header values.

Returned if a new subscription was created in response to your request.
*/
type UpdateProfileCreated struct {
}

func (o *UpdateProfileCreated) Error() string {
	return fmt.Sprintf("[POST /1/user/-/profile.json][%d] updateProfileCreated ", 201)
}

func (o *UpdateProfileCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateProfileConflict creates a UpdateProfileConflict with default headers values
func NewUpdateProfileConflict() *UpdateProfileConflict {
	return &UpdateProfileConflict{}
}

/*UpdateProfileConflict handles this case with default header values.

Returned if the given user is already subscribed to this stream using a different subscription ID, OR if the given subscription ID is already used to identify a subscription to a different stream.
*/
type UpdateProfileConflict struct {
}

func (o *UpdateProfileConflict) Error() string {
	return fmt.Sprintf("[POST /1/user/-/profile.json][%d] updateProfileConflict ", 409)
}

func (o *UpdateProfileConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
