// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteSubscriptionsReader is a Reader for the DeleteSubscriptions structure.
type DeleteSubscriptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSubscriptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewDeleteSubscriptionsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewDeleteSubscriptionsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewDeleteSubscriptionsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSubscriptionsCreated creates a DeleteSubscriptionsCreated with default headers values
func NewDeleteSubscriptionsCreated() *DeleteSubscriptionsCreated {
	return &DeleteSubscriptionsCreated{}
}

/*DeleteSubscriptionsCreated handles this case with default header values.

Returned if a new subscription was created in response to your request.
*/
type DeleteSubscriptionsCreated struct {
}

func (o *DeleteSubscriptionsCreated) Error() string {
	return fmt.Sprintf("[DELETE /1/user/-/{collection-path}/apiSubscriptions/{subscription-id}.json][%d] deleteSubscriptionsCreated ", 201)
}

func (o *DeleteSubscriptionsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSubscriptionsNoContent creates a DeleteSubscriptionsNoContent with default headers values
func NewDeleteSubscriptionsNoContent() *DeleteSubscriptionsNoContent {
	return &DeleteSubscriptionsNoContent{}
}

/*DeleteSubscriptionsNoContent handles this case with default header values.

A successful request.
*/
type DeleteSubscriptionsNoContent struct {
}

func (o *DeleteSubscriptionsNoContent) Error() string {
	return fmt.Sprintf("[DELETE /1/user/-/{collection-path}/apiSubscriptions/{subscription-id}.json][%d] deleteSubscriptionsNoContent ", 204)
}

func (o *DeleteSubscriptionsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSubscriptionsConflict creates a DeleteSubscriptionsConflict with default headers values
func NewDeleteSubscriptionsConflict() *DeleteSubscriptionsConflict {
	return &DeleteSubscriptionsConflict{}
}

/*DeleteSubscriptionsConflict handles this case with default header values.

Returned if the given user is already subscribed to this stream using a different subscription ID, OR if the given subscription ID is already used to identify a subscription to a different stream.
*/
type DeleteSubscriptionsConflict struct {
}

func (o *DeleteSubscriptionsConflict) Error() string {
	return fmt.Sprintf("[DELETE /1/user/-/{collection-path}/apiSubscriptions/{subscription-id}.json][%d] deleteSubscriptionsConflict ", 409)
}

func (o *DeleteSubscriptionsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
