// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSubscriptionsListReader is a Reader for the GetSubscriptionsList structure.
type GetSubscriptionsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSubscriptionsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSubscriptionsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewGetSubscriptionsListCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewGetSubscriptionsListConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSubscriptionsListOK creates a GetSubscriptionsListOK with default headers values
func NewGetSubscriptionsListOK() *GetSubscriptionsListOK {
	return &GetSubscriptionsListOK{}
}

/*GetSubscriptionsListOK handles this case with default header values.

Returned if the given user is already subscribed to the stream.
*/
type GetSubscriptionsListOK struct {
}

func (o *GetSubscriptionsListOK) Error() string {
	return fmt.Sprintf("[GET /1/user/-/{collection-path}/apiSubscriptions.json][%d] getSubscriptionsListOK ", 200)
}

func (o *GetSubscriptionsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSubscriptionsListCreated creates a GetSubscriptionsListCreated with default headers values
func NewGetSubscriptionsListCreated() *GetSubscriptionsListCreated {
	return &GetSubscriptionsListCreated{}
}

/*GetSubscriptionsListCreated handles this case with default header values.

Returned if a new subscription was created in response to your request.
*/
type GetSubscriptionsListCreated struct {
}

func (o *GetSubscriptionsListCreated) Error() string {
	return fmt.Sprintf("[GET /1/user/-/{collection-path}/apiSubscriptions.json][%d] getSubscriptionsListCreated ", 201)
}

func (o *GetSubscriptionsListCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSubscriptionsListConflict creates a GetSubscriptionsListConflict with default headers values
func NewGetSubscriptionsListConflict() *GetSubscriptionsListConflict {
	return &GetSubscriptionsListConflict{}
}

/*GetSubscriptionsListConflict handles this case with default header values.

Returned if the given user is already subscribed to this stream using a different subscription ID, OR if the given subscription ID is already used to identify a subscription to a different stream.
*/
type GetSubscriptionsListConflict struct {
}

func (o *GetSubscriptionsListConflict) Error() string {
	return fmt.Sprintf("[GET /1/user/-/{collection-path}/apiSubscriptions.json][%d] getSubscriptionsListConflict ", 409)
}

func (o *GetSubscriptionsListConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
