// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSubscriptionsListParams creates a new GetSubscriptionsListParams object
// with the default values initialized.
func NewGetSubscriptionsListParams() *GetSubscriptionsListParams {
	var ()
	return &GetSubscriptionsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSubscriptionsListParamsWithTimeout creates a new GetSubscriptionsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSubscriptionsListParamsWithTimeout(timeout time.Duration) *GetSubscriptionsListParams {
	var ()
	return &GetSubscriptionsListParams{

		timeout: timeout,
	}
}

// NewGetSubscriptionsListParamsWithContext creates a new GetSubscriptionsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSubscriptionsListParamsWithContext(ctx context.Context) *GetSubscriptionsListParams {
	var ()
	return &GetSubscriptionsListParams{

		Context: ctx,
	}
}

// NewGetSubscriptionsListParamsWithHTTPClient creates a new GetSubscriptionsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSubscriptionsListParamsWithHTTPClient(client *http.Client) *GetSubscriptionsListParams {
	var ()
	return &GetSubscriptionsListParams{
		HTTPClient: client,
	}
}

/*GetSubscriptionsListParams contains all the parameters to send to the API endpoint
for the get subscriptions list operation typically these are written to a http.Request
*/
type GetSubscriptionsListParams struct {

	/*CollectionPath
	  This is the resource of the collection to receive notifications from (foods, activities, sleep, or body). If not present, subscription will be created for all collections. If you have both all and specific collection subscriptions, you will get duplicate notifications on that collections' updates. Each subscriber can have only one subscription for a specific user's collection.

	*/
	CollectionPath string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get subscriptions list params
func (o *GetSubscriptionsListParams) WithTimeout(timeout time.Duration) *GetSubscriptionsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get subscriptions list params
func (o *GetSubscriptionsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get subscriptions list params
func (o *GetSubscriptionsListParams) WithContext(ctx context.Context) *GetSubscriptionsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get subscriptions list params
func (o *GetSubscriptionsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get subscriptions list params
func (o *GetSubscriptionsListParams) WithHTTPClient(client *http.Client) *GetSubscriptionsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get subscriptions list params
func (o *GetSubscriptionsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollectionPath adds the collectionPath to the get subscriptions list params
func (o *GetSubscriptionsListParams) WithCollectionPath(collectionPath string) *GetSubscriptionsListParams {
	o.SetCollectionPath(collectionPath)
	return o
}

// SetCollectionPath adds the collectionPath to the get subscriptions list params
func (o *GetSubscriptionsListParams) SetCollectionPath(collectionPath string) {
	o.CollectionPath = collectionPath
}

// WriteToRequest writes these params to a swagger request
func (o *GetSubscriptionsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param collection-path
	if err := r.SetPathParam("collection-path", o.CollectionPath); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
