// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteActivitiesLogParams creates a new DeleteActivitiesLogParams object
// with the default values initialized.
func NewDeleteActivitiesLogParams() *DeleteActivitiesLogParams {
	var ()
	return &DeleteActivitiesLogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteActivitiesLogParamsWithTimeout creates a new DeleteActivitiesLogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteActivitiesLogParamsWithTimeout(timeout time.Duration) *DeleteActivitiesLogParams {
	var ()
	return &DeleteActivitiesLogParams{

		timeout: timeout,
	}
}

// NewDeleteActivitiesLogParamsWithContext creates a new DeleteActivitiesLogParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteActivitiesLogParamsWithContext(ctx context.Context) *DeleteActivitiesLogParams {
	var ()
	return &DeleteActivitiesLogParams{

		Context: ctx,
	}
}

// NewDeleteActivitiesLogParamsWithHTTPClient creates a new DeleteActivitiesLogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteActivitiesLogParamsWithHTTPClient(client *http.Client) *DeleteActivitiesLogParams {
	var ()
	return &DeleteActivitiesLogParams{
		HTTPClient: client,
	}
}

/*DeleteActivitiesLogParams contains all the parameters to send to the API endpoint
for the delete activities log operation typically these are written to a http.Request
*/
type DeleteActivitiesLogParams struct {

	/*ActivityLogID
	  The id of the activity log entry.

	*/
	ActivityLogID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete activities log params
func (o *DeleteActivitiesLogParams) WithTimeout(timeout time.Duration) *DeleteActivitiesLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete activities log params
func (o *DeleteActivitiesLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete activities log params
func (o *DeleteActivitiesLogParams) WithContext(ctx context.Context) *DeleteActivitiesLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete activities log params
func (o *DeleteActivitiesLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete activities log params
func (o *DeleteActivitiesLogParams) WithHTTPClient(client *http.Client) *DeleteActivitiesLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete activities log params
func (o *DeleteActivitiesLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActivityLogID adds the activityLogID to the delete activities log params
func (o *DeleteActivitiesLogParams) WithActivityLogID(activityLogID int64) *DeleteActivitiesLogParams {
	o.SetActivityLogID(activityLogID)
	return o
}

// SetActivityLogID adds the activityLogId to the delete activities log params
func (o *DeleteActivitiesLogParams) SetActivityLogID(activityLogID int64) {
	o.ActivityLogID = activityLogID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteActivitiesLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param activity-log-id
	if err := r.SetPathParam("activity-log-id", swag.FormatInt64(o.ActivityLogID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
