// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteFavoriteActivitiesParams creates a new DeleteFavoriteActivitiesParams object
// with the default values initialized.
func NewDeleteFavoriteActivitiesParams() *DeleteFavoriteActivitiesParams {
	var ()
	return &DeleteFavoriteActivitiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFavoriteActivitiesParamsWithTimeout creates a new DeleteFavoriteActivitiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFavoriteActivitiesParamsWithTimeout(timeout time.Duration) *DeleteFavoriteActivitiesParams {
	var ()
	return &DeleteFavoriteActivitiesParams{

		timeout: timeout,
	}
}

// NewDeleteFavoriteActivitiesParamsWithContext creates a new DeleteFavoriteActivitiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFavoriteActivitiesParamsWithContext(ctx context.Context) *DeleteFavoriteActivitiesParams {
	var ()
	return &DeleteFavoriteActivitiesParams{

		Context: ctx,
	}
}

// NewDeleteFavoriteActivitiesParamsWithHTTPClient creates a new DeleteFavoriteActivitiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFavoriteActivitiesParamsWithHTTPClient(client *http.Client) *DeleteFavoriteActivitiesParams {
	var ()
	return &DeleteFavoriteActivitiesParams{
		HTTPClient: client,
	}
}

/*DeleteFavoriteActivitiesParams contains all the parameters to send to the API endpoint
for the delete favorite activities operation typically these are written to a http.Request
*/
type DeleteFavoriteActivitiesParams struct {

	/*ActivityID
	  The ID of the activity to be removed.

	*/
	ActivityID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete favorite activities params
func (o *DeleteFavoriteActivitiesParams) WithTimeout(timeout time.Duration) *DeleteFavoriteActivitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete favorite activities params
func (o *DeleteFavoriteActivitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete favorite activities params
func (o *DeleteFavoriteActivitiesParams) WithContext(ctx context.Context) *DeleteFavoriteActivitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete favorite activities params
func (o *DeleteFavoriteActivitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete favorite activities params
func (o *DeleteFavoriteActivitiesParams) WithHTTPClient(client *http.Client) *DeleteFavoriteActivitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete favorite activities params
func (o *DeleteFavoriteActivitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActivityID adds the activityID to the delete favorite activities params
func (o *DeleteFavoriteActivitiesParams) WithActivityID(activityID string) *DeleteFavoriteActivitiesParams {
	o.SetActivityID(activityID)
	return o
}

// SetActivityID adds the activityId to the delete favorite activities params
func (o *DeleteFavoriteActivitiesParams) SetActivityID(activityID string) {
	o.ActivityID = activityID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFavoriteActivitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param activity-id
	if err := r.SetPathParam("activity-id", o.ActivityID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
