// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetActivitiesTypeDetailParams creates a new GetActivitiesTypeDetailParams object
// with the default values initialized.
func NewGetActivitiesTypeDetailParams() *GetActivitiesTypeDetailParams {
	var ()
	return &GetActivitiesTypeDetailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActivitiesTypeDetailParamsWithTimeout creates a new GetActivitiesTypeDetailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActivitiesTypeDetailParamsWithTimeout(timeout time.Duration) *GetActivitiesTypeDetailParams {
	var ()
	return &GetActivitiesTypeDetailParams{

		timeout: timeout,
	}
}

// NewGetActivitiesTypeDetailParamsWithContext creates a new GetActivitiesTypeDetailParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActivitiesTypeDetailParamsWithContext(ctx context.Context) *GetActivitiesTypeDetailParams {
	var ()
	return &GetActivitiesTypeDetailParams{

		Context: ctx,
	}
}

// NewGetActivitiesTypeDetailParamsWithHTTPClient creates a new GetActivitiesTypeDetailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActivitiesTypeDetailParamsWithHTTPClient(client *http.Client) *GetActivitiesTypeDetailParams {
	var ()
	return &GetActivitiesTypeDetailParams{
		HTTPClient: client,
	}
}

/*GetActivitiesTypeDetailParams contains all the parameters to send to the API endpoint
for the get activities type detail operation typically these are written to a http.Request
*/
type GetActivitiesTypeDetailParams struct {

	/*ActivityID
	  The activity ID.

	*/
	ActivityID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get activities type detail params
func (o *GetActivitiesTypeDetailParams) WithTimeout(timeout time.Duration) *GetActivitiesTypeDetailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get activities type detail params
func (o *GetActivitiesTypeDetailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get activities type detail params
func (o *GetActivitiesTypeDetailParams) WithContext(ctx context.Context) *GetActivitiesTypeDetailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get activities type detail params
func (o *GetActivitiesTypeDetailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get activities type detail params
func (o *GetActivitiesTypeDetailParams) WithHTTPClient(client *http.Client) *GetActivitiesTypeDetailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get activities type detail params
func (o *GetActivitiesTypeDetailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActivityID adds the activityID to the get activities type detail params
func (o *GetActivitiesTypeDetailParams) WithActivityID(activityID string) *GetActivitiesTypeDetailParams {
	o.SetActivityID(activityID)
	return o
}

// SetActivityID adds the activityId to the get activities type detail params
func (o *GetActivitiesTypeDetailParams) SetActivityID(activityID string) {
	o.ActivityID = activityID
}

// WriteToRequest writes these params to a swagger request
func (o *GetActivitiesTypeDetailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param activity-id
	if err := r.SetPathParam("activity-id", o.ActivityID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
