// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRecentActivitiesParams creates a new GetRecentActivitiesParams object
// with the default values initialized.
func NewGetRecentActivitiesParams() *GetRecentActivitiesParams {

	return &GetRecentActivitiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRecentActivitiesParamsWithTimeout creates a new GetRecentActivitiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRecentActivitiesParamsWithTimeout(timeout time.Duration) *GetRecentActivitiesParams {

	return &GetRecentActivitiesParams{

		timeout: timeout,
	}
}

// NewGetRecentActivitiesParamsWithContext creates a new GetRecentActivitiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRecentActivitiesParamsWithContext(ctx context.Context) *GetRecentActivitiesParams {

	return &GetRecentActivitiesParams{

		Context: ctx,
	}
}

// NewGetRecentActivitiesParamsWithHTTPClient creates a new GetRecentActivitiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRecentActivitiesParamsWithHTTPClient(client *http.Client) *GetRecentActivitiesParams {

	return &GetRecentActivitiesParams{
		HTTPClient: client,
	}
}

/*GetRecentActivitiesParams contains all the parameters to send to the API endpoint
for the get recent activities operation typically these are written to a http.Request
*/
type GetRecentActivitiesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get recent activities params
func (o *GetRecentActivitiesParams) WithTimeout(timeout time.Duration) *GetRecentActivitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get recent activities params
func (o *GetRecentActivitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get recent activities params
func (o *GetRecentActivitiesParams) WithContext(ctx context.Context) *GetRecentActivitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get recent activities params
func (o *GetRecentActivitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get recent activities params
func (o *GetRecentActivitiesParams) WithHTTPClient(client *http.Client) *GetRecentActivitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get recent activities params
func (o *GetRecentActivitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRecentActivitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
