// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetActivitiesTypesParams creates a new GetActivitiesTypesParams object
// with the default values initialized.
func NewGetActivitiesTypesParams() *GetActivitiesTypesParams {

	return &GetActivitiesTypesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActivitiesTypesParamsWithTimeout creates a new GetActivitiesTypesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActivitiesTypesParamsWithTimeout(timeout time.Duration) *GetActivitiesTypesParams {

	return &GetActivitiesTypesParams{

		timeout: timeout,
	}
}

// NewGetActivitiesTypesParamsWithContext creates a new GetActivitiesTypesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActivitiesTypesParamsWithContext(ctx context.Context) *GetActivitiesTypesParams {

	return &GetActivitiesTypesParams{

		Context: ctx,
	}
}

// NewGetActivitiesTypesParamsWithHTTPClient creates a new GetActivitiesTypesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActivitiesTypesParamsWithHTTPClient(client *http.Client) *GetActivitiesTypesParams {

	return &GetActivitiesTypesParams{
		HTTPClient: client,
	}
}

/*GetActivitiesTypesParams contains all the parameters to send to the API endpoint
for the get activities types operation typically these are written to a http.Request
*/
type GetActivitiesTypesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get activities types params
func (o *GetActivitiesTypesParams) WithTimeout(timeout time.Duration) *GetActivitiesTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get activities types params
func (o *GetActivitiesTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get activities types params
func (o *GetActivitiesTypesParams) WithContext(ctx context.Context) *GetActivitiesTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get activities types params
func (o *GetActivitiesTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get activities types params
func (o *GetActivitiesTypesParams) WithHTTPClient(client *http.Client) *GetActivitiesTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get activities types params
func (o *GetActivitiesTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetActivitiesTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
