// Code generated by go-swagger; DO NOT EDIT.

package time_series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetActivitiesTrackerResourceByDateRangeParams creates a new GetActivitiesTrackerResourceByDateRangeParams object
// with the default values initialized.
func NewGetActivitiesTrackerResourceByDateRangeParams() *GetActivitiesTrackerResourceByDateRangeParams {
	var (
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesTrackerResourceByDateRangeParams{
		ResourcePath: resourcePathDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActivitiesTrackerResourceByDateRangeParamsWithTimeout creates a new GetActivitiesTrackerResourceByDateRangeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActivitiesTrackerResourceByDateRangeParamsWithTimeout(timeout time.Duration) *GetActivitiesTrackerResourceByDateRangeParams {
	var (
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesTrackerResourceByDateRangeParams{
		ResourcePath: resourcePathDefault,

		timeout: timeout,
	}
}

// NewGetActivitiesTrackerResourceByDateRangeParamsWithContext creates a new GetActivitiesTrackerResourceByDateRangeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActivitiesTrackerResourceByDateRangeParamsWithContext(ctx context.Context) *GetActivitiesTrackerResourceByDateRangeParams {
	var (
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesTrackerResourceByDateRangeParams{
		ResourcePath: resourcePathDefault,

		Context: ctx,
	}
}

// NewGetActivitiesTrackerResourceByDateRangeParamsWithHTTPClient creates a new GetActivitiesTrackerResourceByDateRangeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActivitiesTrackerResourceByDateRangeParamsWithHTTPClient(client *http.Client) *GetActivitiesTrackerResourceByDateRangeParams {
	var (
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesTrackerResourceByDateRangeParams{
		ResourcePath: resourcePathDefault,
		HTTPClient:   client,
	}
}

/*GetActivitiesTrackerResourceByDateRangeParams contains all the parameters to send to the API endpoint
for the get activities tracker resource by date range operation typically these are written to a http.Request
*/
type GetActivitiesTrackerResourceByDateRangeParams struct {

	/*BaseDate
	  The range start date in the format yyyy-MM-dd or today.

	*/
	BaseDate strfmt.Date
	/*EndDate
	  The end date of the range.

	*/
	EndDate strfmt.Date
	/*ResourcePath
	  The resource-path; see options in the Resource Path Options section in the full documentation.

	*/
	ResourcePath string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) WithTimeout(timeout time.Duration) *GetActivitiesTrackerResourceByDateRangeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) WithContext(ctx context.Context) *GetActivitiesTrackerResourceByDateRangeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) WithHTTPClient(client *http.Client) *GetActivitiesTrackerResourceByDateRangeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseDate adds the baseDate to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) WithBaseDate(baseDate strfmt.Date) *GetActivitiesTrackerResourceByDateRangeParams {
	o.SetBaseDate(baseDate)
	return o
}

// SetBaseDate adds the baseDate to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) SetBaseDate(baseDate strfmt.Date) {
	o.BaseDate = baseDate
}

// WithEndDate adds the endDate to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) WithEndDate(endDate strfmt.Date) *GetActivitiesTrackerResourceByDateRangeParams {
	o.SetEndDate(endDate)
	return o
}

// SetEndDate adds the endDate to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) SetEndDate(endDate strfmt.Date) {
	o.EndDate = endDate
}

// WithResourcePath adds the resourcePath to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) WithResourcePath(resourcePath string) *GetActivitiesTrackerResourceByDateRangeParams {
	o.SetResourcePath(resourcePath)
	return o
}

// SetResourcePath adds the resourcePath to the get activities tracker resource by date range params
func (o *GetActivitiesTrackerResourceByDateRangeParams) SetResourcePath(resourcePath string) {
	o.ResourcePath = resourcePath
}

// WriteToRequest writes these params to a swagger request
func (o *GetActivitiesTrackerResourceByDateRangeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param base-date
	if err := r.SetPathParam("base-date", o.BaseDate.String()); err != nil {
		return err
	}

	// path param end-date
	if err := r.SetPathParam("end-date", o.EndDate.String()); err != nil {
		return err
	}

	// path param resource-path
	if err := r.SetPathParam("resource-path", o.ResourcePath); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
