// Code generated by go-swagger; DO NOT EDIT.

package time_series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFoodsByDateRangeParams creates a new GetFoodsByDateRangeParams object
// with the default values initialized.
func NewGetFoodsByDateRangeParams() *GetFoodsByDateRangeParams {
	var (
		resourcePathDefault = string("caloriesIn")
	)
	return &GetFoodsByDateRangeParams{
		ResourcePath: resourcePathDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFoodsByDateRangeParamsWithTimeout creates a new GetFoodsByDateRangeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFoodsByDateRangeParamsWithTimeout(timeout time.Duration) *GetFoodsByDateRangeParams {
	var (
		resourcePathDefault = string("caloriesIn")
	)
	return &GetFoodsByDateRangeParams{
		ResourcePath: resourcePathDefault,

		timeout: timeout,
	}
}

// NewGetFoodsByDateRangeParamsWithContext creates a new GetFoodsByDateRangeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFoodsByDateRangeParamsWithContext(ctx context.Context) *GetFoodsByDateRangeParams {
	var (
		resourcePathDefault = string("caloriesIn")
	)
	return &GetFoodsByDateRangeParams{
		ResourcePath: resourcePathDefault,

		Context: ctx,
	}
}

// NewGetFoodsByDateRangeParamsWithHTTPClient creates a new GetFoodsByDateRangeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFoodsByDateRangeParamsWithHTTPClient(client *http.Client) *GetFoodsByDateRangeParams {
	var (
		resourcePathDefault = string("caloriesIn")
	)
	return &GetFoodsByDateRangeParams{
		ResourcePath: resourcePathDefault,
		HTTPClient:   client,
	}
}

/*GetFoodsByDateRangeParams contains all the parameters to send to the API endpoint
for the get foods by date range operation typically these are written to a http.Request
*/
type GetFoodsByDateRangeParams struct {

	/*BaseDate
	  The range start date in the format yyyy-MM-dd or today.

	*/
	BaseDate strfmt.Date
	/*EndDate
	  The end date of the range.

	*/
	EndDate strfmt.Date
	/*ResourcePath
	  The resouce path. See options in the Resouce Path Options section in the full documentation.

	*/
	ResourcePath string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get foods by date range params
func (o *GetFoodsByDateRangeParams) WithTimeout(timeout time.Duration) *GetFoodsByDateRangeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get foods by date range params
func (o *GetFoodsByDateRangeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get foods by date range params
func (o *GetFoodsByDateRangeParams) WithContext(ctx context.Context) *GetFoodsByDateRangeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get foods by date range params
func (o *GetFoodsByDateRangeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get foods by date range params
func (o *GetFoodsByDateRangeParams) WithHTTPClient(client *http.Client) *GetFoodsByDateRangeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get foods by date range params
func (o *GetFoodsByDateRangeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseDate adds the baseDate to the get foods by date range params
func (o *GetFoodsByDateRangeParams) WithBaseDate(baseDate strfmt.Date) *GetFoodsByDateRangeParams {
	o.SetBaseDate(baseDate)
	return o
}

// SetBaseDate adds the baseDate to the get foods by date range params
func (o *GetFoodsByDateRangeParams) SetBaseDate(baseDate strfmt.Date) {
	o.BaseDate = baseDate
}

// WithEndDate adds the endDate to the get foods by date range params
func (o *GetFoodsByDateRangeParams) WithEndDate(endDate strfmt.Date) *GetFoodsByDateRangeParams {
	o.SetEndDate(endDate)
	return o
}

// SetEndDate adds the endDate to the get foods by date range params
func (o *GetFoodsByDateRangeParams) SetEndDate(endDate strfmt.Date) {
	o.EndDate = endDate
}

// WithResourcePath adds the resourcePath to the get foods by date range params
func (o *GetFoodsByDateRangeParams) WithResourcePath(resourcePath string) *GetFoodsByDateRangeParams {
	o.SetResourcePath(resourcePath)
	return o
}

// SetResourcePath adds the resourcePath to the get foods by date range params
func (o *GetFoodsByDateRangeParams) SetResourcePath(resourcePath string) {
	o.ResourcePath = resourcePath
}

// WriteToRequest writes these params to a swagger request
func (o *GetFoodsByDateRangeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param base-date
	if err := r.SetPathParam("base-date", o.BaseDate.String()); err != nil {
		return err
	}

	// path param end-date
	if err := r.SetPathParam("end-date", o.EndDate.String()); err != nil {
		return err
	}

	// path param resource-path
	if err := r.SetPathParam("resource-path", o.ResourcePath); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
