// Code generated by go-swagger; DO NOT EDIT.

package time_series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetActivitiesResourceByDateRangeTimeSeriesIntradayParams creates a new GetActivitiesResourceByDateRangeTimeSeriesIntradayParams object
// with the default values initialized.
func NewGetActivitiesResourceByDateRangeTimeSeriesIntradayParams() *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	var (
		detailLevelDefault  = string("1min")
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesResourceByDateRangeTimeSeriesIntradayParams{
		DetailLevel:  detailLevelDefault,
		ResourcePath: resourcePathDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActivitiesResourceByDateRangeTimeSeriesIntradayParamsWithTimeout creates a new GetActivitiesResourceByDateRangeTimeSeriesIntradayParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActivitiesResourceByDateRangeTimeSeriesIntradayParamsWithTimeout(timeout time.Duration) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	var (
		detailLevelDefault  = string("1min")
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesResourceByDateRangeTimeSeriesIntradayParams{
		DetailLevel:  detailLevelDefault,
		ResourcePath: resourcePathDefault,

		timeout: timeout,
	}
}

// NewGetActivitiesResourceByDateRangeTimeSeriesIntradayParamsWithContext creates a new GetActivitiesResourceByDateRangeTimeSeriesIntradayParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActivitiesResourceByDateRangeTimeSeriesIntradayParamsWithContext(ctx context.Context) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	var (
		detailLevelDefault  = string("1min")
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesResourceByDateRangeTimeSeriesIntradayParams{
		DetailLevel:  detailLevelDefault,
		ResourcePath: resourcePathDefault,

		Context: ctx,
	}
}

// NewGetActivitiesResourceByDateRangeTimeSeriesIntradayParamsWithHTTPClient creates a new GetActivitiesResourceByDateRangeTimeSeriesIntradayParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActivitiesResourceByDateRangeTimeSeriesIntradayParamsWithHTTPClient(client *http.Client) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	var (
		detailLevelDefault  = string("1min")
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesResourceByDateRangeTimeSeriesIntradayParams{
		DetailLevel:  detailLevelDefault,
		ResourcePath: resourcePathDefault,
		HTTPClient:   client,
	}
}

/*GetActivitiesResourceByDateRangeTimeSeriesIntradayParams contains all the parameters to send to the API endpoint
for the get activities resource by date range time series intraday operation typically these are written to a http.Request
*/
type GetActivitiesResourceByDateRangeTimeSeriesIntradayParams struct {

	/*Date
	  The date in the format yyyy-MM-dd or today.

	*/
	Date strfmt.Date
	/*DetailLevel
	  Number of data points to include. Either 1min or 15min.

	*/
	DetailLevel string
	/*EndDate
	  The date in the format yyyy-MM-dd or today.

	*/
	EndDate strfmt.Date
	/*EndTime
	  The end of the period in the format HH:mm.

	*/
	EndTime string
	/*ResourcePath
	  The resource-path; see options in the Resource Path Options section in the full documentation.

	*/
	ResourcePath string
	/*StartTime
	  The start of the period in the format HH:mm.

	*/
	StartTime string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) WithTimeout(timeout time.Duration) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) WithContext(ctx context.Context) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) WithHTTPClient(client *http.Client) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDate adds the date to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) WithDate(date strfmt.Date) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) SetDate(date strfmt.Date) {
	o.Date = date
}

// WithDetailLevel adds the detailLevel to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) WithDetailLevel(detailLevel string) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	o.SetDetailLevel(detailLevel)
	return o
}

// SetDetailLevel adds the detailLevel to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) SetDetailLevel(detailLevel string) {
	o.DetailLevel = detailLevel
}

// WithEndDate adds the endDate to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) WithEndDate(endDate strfmt.Date) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	o.SetEndDate(endDate)
	return o
}

// SetEndDate adds the endDate to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) SetEndDate(endDate strfmt.Date) {
	o.EndDate = endDate
}

// WithEndTime adds the endTime to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) WithEndTime(endTime string) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	o.SetEndTime(endTime)
	return o
}

// SetEndTime adds the endTime to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) SetEndTime(endTime string) {
	o.EndTime = endTime
}

// WithResourcePath adds the resourcePath to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) WithResourcePath(resourcePath string) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	o.SetResourcePath(resourcePath)
	return o
}

// SetResourcePath adds the resourcePath to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) SetResourcePath(resourcePath string) {
	o.ResourcePath = resourcePath
}

// WithStartTime adds the startTime to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) WithStartTime(startTime string) *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the get activities resource by date range time series intraday params
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) SetStartTime(startTime string) {
	o.StartTime = startTime
}

// WriteToRequest writes these params to a swagger request
func (o *GetActivitiesResourceByDateRangeTimeSeriesIntradayParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param date
	if err := r.SetPathParam("date", o.Date.String()); err != nil {
		return err
	}

	// path param detail-level
	if err := r.SetPathParam("detail-level", o.DetailLevel); err != nil {
		return err
	}

	// path param end-date
	if err := r.SetPathParam("end-date", o.EndDate.String()); err != nil {
		return err
	}

	// path param end-time
	if err := r.SetPathParam("end-time", o.EndTime); err != nil {
		return err
	}

	// path param resource-path
	if err := r.SetPathParam("resource-path", o.ResourcePath); err != nil {
		return err
	}

	// path param start-time
	if err := r.SetPathParam("start-time", o.StartTime); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
