// Code generated by go-swagger; DO NOT EDIT.

package time_series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetActivitiesResourceByDateRangeReader is a Reader for the GetActivitiesResourceByDateRange structure.
type GetActivitiesResourceByDateRangeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetActivitiesResourceByDateRangeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetActivitiesResourceByDateRangeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetActivitiesResourceByDateRangeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetActivitiesResourceByDateRangeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetActivitiesResourceByDateRangeConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetActivitiesResourceByDateRangeOK creates a GetActivitiesResourceByDateRangeOK with default headers values
func NewGetActivitiesResourceByDateRangeOK() *GetActivitiesResourceByDateRangeOK {
	return &GetActivitiesResourceByDateRangeOK{}
}

/*GetActivitiesResourceByDateRangeOK handles this case with default header values.

A successful request.
*/
type GetActivitiesResourceByDateRangeOK struct {
}

func (o *GetActivitiesResourceByDateRangeOK) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{base-date}/{end-date}.json][%d] getActivitiesResourceByDateRangeOK ", 200)
}

func (o *GetActivitiesResourceByDateRangeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetActivitiesResourceByDateRangeBadRequest creates a GetActivitiesResourceByDateRangeBadRequest with default headers values
func NewGetActivitiesResourceByDateRangeBadRequest() *GetActivitiesResourceByDateRangeBadRequest {
	return &GetActivitiesResourceByDateRangeBadRequest{}
}

/*GetActivitiesResourceByDateRangeBadRequest handles this case with default header values.

The request had bad syntax or was inherently impossible to be satified.
*/
type GetActivitiesResourceByDateRangeBadRequest struct {
}

func (o *GetActivitiesResourceByDateRangeBadRequest) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{base-date}/{end-date}.json][%d] getActivitiesResourceByDateRangeBadRequest ", 400)
}

func (o *GetActivitiesResourceByDateRangeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetActivitiesResourceByDateRangeUnauthorized creates a GetActivitiesResourceByDateRangeUnauthorized with default headers values
func NewGetActivitiesResourceByDateRangeUnauthorized() *GetActivitiesResourceByDateRangeUnauthorized {
	return &GetActivitiesResourceByDateRangeUnauthorized{}
}

/*GetActivitiesResourceByDateRangeUnauthorized handles this case with default header values.

The request requires user authentication.
*/
type GetActivitiesResourceByDateRangeUnauthorized struct {
}

func (o *GetActivitiesResourceByDateRangeUnauthorized) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{base-date}/{end-date}.json][%d] getActivitiesResourceByDateRangeUnauthorized ", 401)
}

func (o *GetActivitiesResourceByDateRangeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetActivitiesResourceByDateRangeConflict creates a GetActivitiesResourceByDateRangeConflict with default headers values
func NewGetActivitiesResourceByDateRangeConflict() *GetActivitiesResourceByDateRangeConflict {
	return &GetActivitiesResourceByDateRangeConflict{}
}

/*GetActivitiesResourceByDateRangeConflict handles this case with default header values.

Returned if the given user is already subscribed to this stream using a different subscription ID, OR if the given subscription ID is already used to identify a subscription to a different stream.
*/
type GetActivitiesResourceByDateRangeConflict struct {
}

func (o *GetActivitiesResourceByDateRangeConflict) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{base-date}/{end-date}.json][%d] getActivitiesResourceByDateRangeConflict ", 409)
}

func (o *GetActivitiesResourceByDateRangeConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
