// Code generated by go-swagger; DO NOT EDIT.

package time_series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHeartByDateRangeParams creates a new GetHeartByDateRangeParams object
// with the default values initialized.
func NewGetHeartByDateRangeParams() *GetHeartByDateRangeParams {
	var ()
	return &GetHeartByDateRangeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHeartByDateRangeParamsWithTimeout creates a new GetHeartByDateRangeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHeartByDateRangeParamsWithTimeout(timeout time.Duration) *GetHeartByDateRangeParams {
	var ()
	return &GetHeartByDateRangeParams{

		timeout: timeout,
	}
}

// NewGetHeartByDateRangeParamsWithContext creates a new GetHeartByDateRangeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHeartByDateRangeParamsWithContext(ctx context.Context) *GetHeartByDateRangeParams {
	var ()
	return &GetHeartByDateRangeParams{

		Context: ctx,
	}
}

// NewGetHeartByDateRangeParamsWithHTTPClient creates a new GetHeartByDateRangeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHeartByDateRangeParamsWithHTTPClient(client *http.Client) *GetHeartByDateRangeParams {
	var ()
	return &GetHeartByDateRangeParams{
		HTTPClient: client,
	}
}

/*GetHeartByDateRangeParams contains all the parameters to send to the API endpoint
for the get heart by date range operation typically these are written to a http.Request
*/
type GetHeartByDateRangeParams struct {

	/*BaseDate
	  The range start date in  the format yyyy-MM-dd or today.

	*/
	BaseDate string
	/*EndDate
	  The end date of the range.

	*/
	EndDate strfmt.Date

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get heart by date range params
func (o *GetHeartByDateRangeParams) WithTimeout(timeout time.Duration) *GetHeartByDateRangeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get heart by date range params
func (o *GetHeartByDateRangeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get heart by date range params
func (o *GetHeartByDateRangeParams) WithContext(ctx context.Context) *GetHeartByDateRangeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get heart by date range params
func (o *GetHeartByDateRangeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get heart by date range params
func (o *GetHeartByDateRangeParams) WithHTTPClient(client *http.Client) *GetHeartByDateRangeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get heart by date range params
func (o *GetHeartByDateRangeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseDate adds the baseDate to the get heart by date range params
func (o *GetHeartByDateRangeParams) WithBaseDate(baseDate string) *GetHeartByDateRangeParams {
	o.SetBaseDate(baseDate)
	return o
}

// SetBaseDate adds the baseDate to the get heart by date range params
func (o *GetHeartByDateRangeParams) SetBaseDate(baseDate string) {
	o.BaseDate = baseDate
}

// WithEndDate adds the endDate to the get heart by date range params
func (o *GetHeartByDateRangeParams) WithEndDate(endDate strfmt.Date) *GetHeartByDateRangeParams {
	o.SetEndDate(endDate)
	return o
}

// SetEndDate adds the endDate to the get heart by date range params
func (o *GetHeartByDateRangeParams) SetEndDate(endDate strfmt.Date) {
	o.EndDate = endDate
}

// WriteToRequest writes these params to a swagger request
func (o *GetHeartByDateRangeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param base-date
	if err := r.SetPathParam("base-date", o.BaseDate); err != nil {
		return err
	}

	// path param end-date
	if err := r.SetPathParam("end-date", o.EndDate.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
