// Code generated by go-swagger; DO NOT EDIT.

package time_series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetHeartByDateTimestampIntradayReader is a Reader for the GetHeartByDateTimestampIntraday structure.
type GetHeartByDateTimestampIntradayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHeartByDateTimestampIntradayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetHeartByDateTimestampIntradayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetHeartByDateTimestampIntradayUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetHeartByDateTimestampIntradayForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetHeartByDateTimestampIntradayOK creates a GetHeartByDateTimestampIntradayOK with default headers values
func NewGetHeartByDateTimestampIntradayOK() *GetHeartByDateTimestampIntradayOK {
	return &GetHeartByDateTimestampIntradayOK{}
}

/*GetHeartByDateTimestampIntradayOK handles this case with default header values.

Successful request.
*/
type GetHeartByDateTimestampIntradayOK struct {
}

func (o *GetHeartByDateTimestampIntradayOK) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/heart/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json][%d] getHeartByDateTimestampIntradayOK ", 200)
}

func (o *GetHeartByDateTimestampIntradayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHeartByDateTimestampIntradayUnauthorized creates a GetHeartByDateTimestampIntradayUnauthorized with default headers values
func NewGetHeartByDateTimestampIntradayUnauthorized() *GetHeartByDateTimestampIntradayUnauthorized {
	return &GetHeartByDateTimestampIntradayUnauthorized{}
}

/*GetHeartByDateTimestampIntradayUnauthorized handles this case with default header values.

The request requires user authentication.
*/
type GetHeartByDateTimestampIntradayUnauthorized struct {
}

func (o *GetHeartByDateTimestampIntradayUnauthorized) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/heart/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json][%d] getHeartByDateTimestampIntradayUnauthorized ", 401)
}

func (o *GetHeartByDateTimestampIntradayUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHeartByDateTimestampIntradayForbidden creates a GetHeartByDateTimestampIntradayForbidden with default headers values
func NewGetHeartByDateTimestampIntradayForbidden() *GetHeartByDateTimestampIntradayForbidden {
	return &GetHeartByDateTimestampIntradayForbidden{}
}

/*GetHeartByDateTimestampIntradayForbidden handles this case with default header values.

The server understood the request, but is refusing to fulfill it.
*/
type GetHeartByDateTimestampIntradayForbidden struct {
}

func (o *GetHeartByDateTimestampIntradayForbidden) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/heart/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json][%d] getHeartByDateTimestampIntradayForbidden ", 403)
}

func (o *GetHeartByDateTimestampIntradayForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
