// Code generated by go-swagger; DO NOT EDIT.

package time_series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetActivitiesResourceByDateIntradayParams creates a new GetActivitiesResourceByDateIntradayParams object
// with the default values initialized.
func NewGetActivitiesResourceByDateIntradayParams() *GetActivitiesResourceByDateIntradayParams {
	var (
		detailLevelDefault  = string("1min")
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesResourceByDateIntradayParams{
		DetailLevel:  detailLevelDefault,
		ResourcePath: resourcePathDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActivitiesResourceByDateIntradayParamsWithTimeout creates a new GetActivitiesResourceByDateIntradayParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActivitiesResourceByDateIntradayParamsWithTimeout(timeout time.Duration) *GetActivitiesResourceByDateIntradayParams {
	var (
		detailLevelDefault  = string("1min")
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesResourceByDateIntradayParams{
		DetailLevel:  detailLevelDefault,
		ResourcePath: resourcePathDefault,

		timeout: timeout,
	}
}

// NewGetActivitiesResourceByDateIntradayParamsWithContext creates a new GetActivitiesResourceByDateIntradayParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActivitiesResourceByDateIntradayParamsWithContext(ctx context.Context) *GetActivitiesResourceByDateIntradayParams {
	var (
		detailLevelDefault  = string("1min")
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesResourceByDateIntradayParams{
		DetailLevel:  detailLevelDefault,
		ResourcePath: resourcePathDefault,

		Context: ctx,
	}
}

// NewGetActivitiesResourceByDateIntradayParamsWithHTTPClient creates a new GetActivitiesResourceByDateIntradayParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActivitiesResourceByDateIntradayParamsWithHTTPClient(client *http.Client) *GetActivitiesResourceByDateIntradayParams {
	var (
		detailLevelDefault  = string("1min")
		resourcePathDefault = string("steps")
	)
	return &GetActivitiesResourceByDateIntradayParams{
		DetailLevel:  detailLevelDefault,
		ResourcePath: resourcePathDefault,
		HTTPClient:   client,
	}
}

/*GetActivitiesResourceByDateIntradayParams contains all the parameters to send to the API endpoint
for the get activities resource by date intraday operation typically these are written to a http.Request
*/
type GetActivitiesResourceByDateIntradayParams struct {

	/*Date
	  The date in the format yyyy-MM-dd or today.

	*/
	Date strfmt.Date
	/*DetailLevel
	  Number of data points to include. Either 1min or 15min. Optional.

	*/
	DetailLevel string
	/*ResourcePath
	  The resource-path; see options in the Resource Path Options section in the full documentation.

	*/
	ResourcePath string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) WithTimeout(timeout time.Duration) *GetActivitiesResourceByDateIntradayParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) WithContext(ctx context.Context) *GetActivitiesResourceByDateIntradayParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) WithHTTPClient(client *http.Client) *GetActivitiesResourceByDateIntradayParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDate adds the date to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) WithDate(date strfmt.Date) *GetActivitiesResourceByDateIntradayParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) SetDate(date strfmt.Date) {
	o.Date = date
}

// WithDetailLevel adds the detailLevel to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) WithDetailLevel(detailLevel string) *GetActivitiesResourceByDateIntradayParams {
	o.SetDetailLevel(detailLevel)
	return o
}

// SetDetailLevel adds the detailLevel to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) SetDetailLevel(detailLevel string) {
	o.DetailLevel = detailLevel
}

// WithResourcePath adds the resourcePath to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) WithResourcePath(resourcePath string) *GetActivitiesResourceByDateIntradayParams {
	o.SetResourcePath(resourcePath)
	return o
}

// SetResourcePath adds the resourcePath to the get activities resource by date intraday params
func (o *GetActivitiesResourceByDateIntradayParams) SetResourcePath(resourcePath string) {
	o.ResourcePath = resourcePath
}

// WriteToRequest writes these params to a swagger request
func (o *GetActivitiesResourceByDateIntradayParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param date
	if err := r.SetPathParam("date", o.Date.String()); err != nil {
		return err
	}

	// path param detail-level
	if err := r.SetPathParam("detail-level", o.DetailLevel); err != nil {
		return err
	}

	// path param resource-path
	if err := r.SetPathParam("resource-path", o.ResourcePath); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
