// Code generated by go-swagger; DO NOT EDIT.

package time_series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetActivitiesResourceByDateTimeSeriesIntradayReader is a Reader for the GetActivitiesResourceByDateTimeSeriesIntraday structure.
type GetActivitiesResourceByDateTimeSeriesIntradayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetActivitiesResourceByDateTimeSeriesIntradayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetActivitiesResourceByDateTimeSeriesIntradayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetActivitiesResourceByDateTimeSeriesIntradayBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetActivitiesResourceByDateTimeSeriesIntradayUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetActivitiesResourceByDateTimeSeriesIntradayConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetActivitiesResourceByDateTimeSeriesIntradayOK creates a GetActivitiesResourceByDateTimeSeriesIntradayOK with default headers values
func NewGetActivitiesResourceByDateTimeSeriesIntradayOK() *GetActivitiesResourceByDateTimeSeriesIntradayOK {
	return &GetActivitiesResourceByDateTimeSeriesIntradayOK{}
}

/*GetActivitiesResourceByDateTimeSeriesIntradayOK handles this case with default header values.

A successful request.
*/
type GetActivitiesResourceByDateTimeSeriesIntradayOK struct {
}

func (o *GetActivitiesResourceByDateTimeSeriesIntradayOK) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json][%d] getActivitiesResourceByDateTimeSeriesIntradayOK ", 200)
}

func (o *GetActivitiesResourceByDateTimeSeriesIntradayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetActivitiesResourceByDateTimeSeriesIntradayBadRequest creates a GetActivitiesResourceByDateTimeSeriesIntradayBadRequest with default headers values
func NewGetActivitiesResourceByDateTimeSeriesIntradayBadRequest() *GetActivitiesResourceByDateTimeSeriesIntradayBadRequest {
	return &GetActivitiesResourceByDateTimeSeriesIntradayBadRequest{}
}

/*GetActivitiesResourceByDateTimeSeriesIntradayBadRequest handles this case with default header values.

The request had bad syntax or was inherently impossible to be satified.
*/
type GetActivitiesResourceByDateTimeSeriesIntradayBadRequest struct {
}

func (o *GetActivitiesResourceByDateTimeSeriesIntradayBadRequest) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json][%d] getActivitiesResourceByDateTimeSeriesIntradayBadRequest ", 400)
}

func (o *GetActivitiesResourceByDateTimeSeriesIntradayBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetActivitiesResourceByDateTimeSeriesIntradayUnauthorized creates a GetActivitiesResourceByDateTimeSeriesIntradayUnauthorized with default headers values
func NewGetActivitiesResourceByDateTimeSeriesIntradayUnauthorized() *GetActivitiesResourceByDateTimeSeriesIntradayUnauthorized {
	return &GetActivitiesResourceByDateTimeSeriesIntradayUnauthorized{}
}

/*GetActivitiesResourceByDateTimeSeriesIntradayUnauthorized handles this case with default header values.

The request requires user authentication.
*/
type GetActivitiesResourceByDateTimeSeriesIntradayUnauthorized struct {
}

func (o *GetActivitiesResourceByDateTimeSeriesIntradayUnauthorized) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json][%d] getActivitiesResourceByDateTimeSeriesIntradayUnauthorized ", 401)
}

func (o *GetActivitiesResourceByDateTimeSeriesIntradayUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetActivitiesResourceByDateTimeSeriesIntradayConflict creates a GetActivitiesResourceByDateTimeSeriesIntradayConflict with default headers values
func NewGetActivitiesResourceByDateTimeSeriesIntradayConflict() *GetActivitiesResourceByDateTimeSeriesIntradayConflict {
	return &GetActivitiesResourceByDateTimeSeriesIntradayConflict{}
}

/*GetActivitiesResourceByDateTimeSeriesIntradayConflict handles this case with default header values.

Returned if the given user is already subscribed to this stream using a different subscription ID, OR if the given subscription ID is already used to identify a subscription to a different stream.
*/
type GetActivitiesResourceByDateTimeSeriesIntradayConflict struct {
}

func (o *GetActivitiesResourceByDateTimeSeriesIntradayConflict) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json][%d] getActivitiesResourceByDateTimeSeriesIntradayConflict ", 409)
}

func (o *GetActivitiesResourceByDateTimeSeriesIntradayConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
