// Code generated by go-swagger; DO NOT EDIT.

package time_series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetActivitiesResourceByDateIntradayReader is a Reader for the GetActivitiesResourceByDateIntraday structure.
type GetActivitiesResourceByDateIntradayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetActivitiesResourceByDateIntradayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetActivitiesResourceByDateIntradayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetActivitiesResourceByDateIntradayBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetActivitiesResourceByDateIntradayUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetActivitiesResourceByDateIntradayConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetActivitiesResourceByDateIntradayOK creates a GetActivitiesResourceByDateIntradayOK with default headers values
func NewGetActivitiesResourceByDateIntradayOK() *GetActivitiesResourceByDateIntradayOK {
	return &GetActivitiesResourceByDateIntradayOK{}
}

/*GetActivitiesResourceByDateIntradayOK handles this case with default header values.

A successful request.
*/
type GetActivitiesResourceByDateIntradayOK struct {
}

func (o *GetActivitiesResourceByDateIntradayOK) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}.json][%d] getActivitiesResourceByDateIntradayOK ", 200)
}

func (o *GetActivitiesResourceByDateIntradayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetActivitiesResourceByDateIntradayBadRequest creates a GetActivitiesResourceByDateIntradayBadRequest with default headers values
func NewGetActivitiesResourceByDateIntradayBadRequest() *GetActivitiesResourceByDateIntradayBadRequest {
	return &GetActivitiesResourceByDateIntradayBadRequest{}
}

/*GetActivitiesResourceByDateIntradayBadRequest handles this case with default header values.

The request had bad syntax or was inherently impossible to be satified.
*/
type GetActivitiesResourceByDateIntradayBadRequest struct {
}

func (o *GetActivitiesResourceByDateIntradayBadRequest) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}.json][%d] getActivitiesResourceByDateIntradayBadRequest ", 400)
}

func (o *GetActivitiesResourceByDateIntradayBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetActivitiesResourceByDateIntradayUnauthorized creates a GetActivitiesResourceByDateIntradayUnauthorized with default headers values
func NewGetActivitiesResourceByDateIntradayUnauthorized() *GetActivitiesResourceByDateIntradayUnauthorized {
	return &GetActivitiesResourceByDateIntradayUnauthorized{}
}

/*GetActivitiesResourceByDateIntradayUnauthorized handles this case with default header values.

The request requires user authentication.
*/
type GetActivitiesResourceByDateIntradayUnauthorized struct {
}

func (o *GetActivitiesResourceByDateIntradayUnauthorized) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}.json][%d] getActivitiesResourceByDateIntradayUnauthorized ", 401)
}

func (o *GetActivitiesResourceByDateIntradayUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetActivitiesResourceByDateIntradayConflict creates a GetActivitiesResourceByDateIntradayConflict with default headers values
func NewGetActivitiesResourceByDateIntradayConflict() *GetActivitiesResourceByDateIntradayConflict {
	return &GetActivitiesResourceByDateIntradayConflict{}
}

/*GetActivitiesResourceByDateIntradayConflict handles this case with default header values.

Returned if the given user is already subscribed to this stream using a different subscription ID, OR if the given subscription ID is already used to identify a subscription to a different stream.
*/
type GetActivitiesResourceByDateIntradayConflict struct {
}

func (o *GetActivitiesResourceByDateIntradayConflict) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}.json][%d] getActivitiesResourceByDateIntradayConflict ", 409)
}

func (o *GetActivitiesResourceByDateIntradayConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
