// Code generated by go-swagger; DO NOT EDIT.

package time_series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetHeartByDatePeriodReader is a Reader for the GetHeartByDatePeriod structure.
type GetHeartByDatePeriodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHeartByDatePeriodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetHeartByDatePeriodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetHeartByDatePeriodUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetHeartByDatePeriodForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetHeartByDatePeriodOK creates a GetHeartByDatePeriodOK with default headers values
func NewGetHeartByDatePeriodOK() *GetHeartByDatePeriodOK {
	return &GetHeartByDatePeriodOK{}
}

/*GetHeartByDatePeriodOK handles this case with default header values.

Successful request.
*/
type GetHeartByDatePeriodOK struct {
}

func (o *GetHeartByDatePeriodOK) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/heart/date/{date}/{period}.json][%d] getHeartByDatePeriodOK ", 200)
}

func (o *GetHeartByDatePeriodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHeartByDatePeriodUnauthorized creates a GetHeartByDatePeriodUnauthorized with default headers values
func NewGetHeartByDatePeriodUnauthorized() *GetHeartByDatePeriodUnauthorized {
	return &GetHeartByDatePeriodUnauthorized{}
}

/*GetHeartByDatePeriodUnauthorized handles this case with default header values.

The request requires user authentication.
*/
type GetHeartByDatePeriodUnauthorized struct {
}

func (o *GetHeartByDatePeriodUnauthorized) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/heart/date/{date}/{period}.json][%d] getHeartByDatePeriodUnauthorized ", 401)
}

func (o *GetHeartByDatePeriodUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHeartByDatePeriodForbidden creates a GetHeartByDatePeriodForbidden with default headers values
func NewGetHeartByDatePeriodForbidden() *GetHeartByDatePeriodForbidden {
	return &GetHeartByDatePeriodForbidden{}
}

/*GetHeartByDatePeriodForbidden handles this case with default header values.

The server understood the request, but is refusing to fulfill it.
*/
type GetHeartByDatePeriodForbidden struct {
}

func (o *GetHeartByDatePeriodForbidden) Error() string {
	return fmt.Sprintf("[GET /1/user/-/activities/heart/date/{date}/{period}.json][%d] getHeartByDatePeriodForbidden ", 403)
}

func (o *GetHeartByDatePeriodForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
