// Code generated by go-swagger; DO NOT EDIT.

package friends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFriendsLeaderboardParams creates a new GetFriendsLeaderboardParams object
// with the default values initialized.
func NewGetFriendsLeaderboardParams() *GetFriendsLeaderboardParams {

	return &GetFriendsLeaderboardParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFriendsLeaderboardParamsWithTimeout creates a new GetFriendsLeaderboardParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFriendsLeaderboardParamsWithTimeout(timeout time.Duration) *GetFriendsLeaderboardParams {

	return &GetFriendsLeaderboardParams{

		timeout: timeout,
	}
}

// NewGetFriendsLeaderboardParamsWithContext creates a new GetFriendsLeaderboardParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFriendsLeaderboardParamsWithContext(ctx context.Context) *GetFriendsLeaderboardParams {

	return &GetFriendsLeaderboardParams{

		Context: ctx,
	}
}

// NewGetFriendsLeaderboardParamsWithHTTPClient creates a new GetFriendsLeaderboardParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFriendsLeaderboardParamsWithHTTPClient(client *http.Client) *GetFriendsLeaderboardParams {

	return &GetFriendsLeaderboardParams{
		HTTPClient: client,
	}
}

/*GetFriendsLeaderboardParams contains all the parameters to send to the API endpoint
for the get friends leaderboard operation typically these are written to a http.Request
*/
type GetFriendsLeaderboardParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get friends leaderboard params
func (o *GetFriendsLeaderboardParams) WithTimeout(timeout time.Duration) *GetFriendsLeaderboardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get friends leaderboard params
func (o *GetFriendsLeaderboardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get friends leaderboard params
func (o *GetFriendsLeaderboardParams) WithContext(ctx context.Context) *GetFriendsLeaderboardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get friends leaderboard params
func (o *GetFriendsLeaderboardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get friends leaderboard params
func (o *GetFriendsLeaderboardParams) WithHTTPClient(client *http.Client) *GetFriendsLeaderboardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get friends leaderboard params
func (o *GetFriendsLeaderboardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetFriendsLeaderboardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
