// Code generated by go-swagger; DO NOT EDIT.

package friends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetFriendsReader is a Reader for the GetFriends structure.
type GetFriendsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFriendsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetFriendsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewGetFriendsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetFriendsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetFriendsOK creates a GetFriendsOK with default headers values
func NewGetFriendsOK() *GetFriendsOK {
	return &GetFriendsOK{}
}

/*GetFriendsOK handles this case with default header values.

Successful request.
*/
type GetFriendsOK struct {
}

func (o *GetFriendsOK) Error() string {
	return fmt.Sprintf("[GET /1/user/-/friends.json][%d] getFriendsOK ", 200)
}

func (o *GetFriendsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFriendsCreated creates a GetFriendsCreated with default headers values
func NewGetFriendsCreated() *GetFriendsCreated {
	return &GetFriendsCreated{}
}

/*GetFriendsCreated handles this case with default header values.

The request has been fulfilled and resulted in a new resource being created.
*/
type GetFriendsCreated struct {
}

func (o *GetFriendsCreated) Error() string {
	return fmt.Sprintf("[GET /1/user/-/friends.json][%d] getFriendsCreated ", 201)
}

func (o *GetFriendsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFriendsUnauthorized creates a GetFriendsUnauthorized with default headers values
func NewGetFriendsUnauthorized() *GetFriendsUnauthorized {
	return &GetFriendsUnauthorized{}
}

/*GetFriendsUnauthorized handles this case with default header values.

The request requires user authentication.
*/
type GetFriendsUnauthorized struct {
}

func (o *GetFriendsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /1/user/-/friends.json][%d] getFriendsUnauthorized ", 401)
}

func (o *GetFriendsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
