// Code generated by go-swagger; DO NOT EDIT.

package body_and_weight

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// AddBodyFatLogReader is a Reader for the AddBodyFatLog structure.
type AddBodyFatLogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddBodyFatLogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAddBodyFatLogOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewAddBodyFatLogCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAddBodyFatLogBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewAddBodyFatLogUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddBodyFatLogOK creates a AddBodyFatLogOK with default headers values
func NewAddBodyFatLogOK() *AddBodyFatLogOK {
	return &AddBodyFatLogOK{}
}

/*AddBodyFatLogOK handles this case with default header values.

A successful request.
*/
type AddBodyFatLogOK struct {
}

func (o *AddBodyFatLogOK) Error() string {
	return fmt.Sprintf("[POST /1/user/-/body/log/fat.json][%d] addBodyFatLogOK ", 200)
}

func (o *AddBodyFatLogOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddBodyFatLogCreated creates a AddBodyFatLogCreated with default headers values
func NewAddBodyFatLogCreated() *AddBodyFatLogCreated {
	return &AddBodyFatLogCreated{}
}

/*AddBodyFatLogCreated handles this case with default header values.

The request has been fulfilled and resulted in a new resouce being created.
*/
type AddBodyFatLogCreated struct {
}

func (o *AddBodyFatLogCreated) Error() string {
	return fmt.Sprintf("[POST /1/user/-/body/log/fat.json][%d] addBodyFatLogCreated ", 201)
}

func (o *AddBodyFatLogCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddBodyFatLogBadRequest creates a AddBodyFatLogBadRequest with default headers values
func NewAddBodyFatLogBadRequest() *AddBodyFatLogBadRequest {
	return &AddBodyFatLogBadRequest{}
}

/*AddBodyFatLogBadRequest handles this case with default header values.

The request had bad syntax or was inherently impossible to be satified.
*/
type AddBodyFatLogBadRequest struct {
}

func (o *AddBodyFatLogBadRequest) Error() string {
	return fmt.Sprintf("[POST /1/user/-/body/log/fat.json][%d] addBodyFatLogBadRequest ", 400)
}

func (o *AddBodyFatLogBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddBodyFatLogUnauthorized creates a AddBodyFatLogUnauthorized with default headers values
func NewAddBodyFatLogUnauthorized() *AddBodyFatLogUnauthorized {
	return &AddBodyFatLogUnauthorized{}
}

/*AddBodyFatLogUnauthorized handles this case with default header values.

The request requires user authentication.
*/
type AddBodyFatLogUnauthorized struct {
}

func (o *AddBodyFatLogUnauthorized) Error() string {
	return fmt.Sprintf("[POST /1/user/-/body/log/fat.json][%d] addBodyFatLogUnauthorized ", 401)
}

func (o *AddBodyFatLogUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
