// Code generated by go-swagger; DO NOT EDIT.

package body_and_weight

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAddBodyFatLogParams creates a new AddBodyFatLogParams object
// with the default values initialized.
func NewAddBodyFatLogParams() *AddBodyFatLogParams {
	var ()
	return &AddBodyFatLogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddBodyFatLogParamsWithTimeout creates a new AddBodyFatLogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddBodyFatLogParamsWithTimeout(timeout time.Duration) *AddBodyFatLogParams {
	var ()
	return &AddBodyFatLogParams{

		timeout: timeout,
	}
}

// NewAddBodyFatLogParamsWithContext creates a new AddBodyFatLogParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddBodyFatLogParamsWithContext(ctx context.Context) *AddBodyFatLogParams {
	var ()
	return &AddBodyFatLogParams{

		Context: ctx,
	}
}

// NewAddBodyFatLogParamsWithHTTPClient creates a new AddBodyFatLogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddBodyFatLogParamsWithHTTPClient(client *http.Client) *AddBodyFatLogParams {
	var ()
	return &AddBodyFatLogParams{
		HTTPClient: client,
	}
}

/*AddBodyFatLogParams contains all the parameters to send to the API endpoint
for the add body fat log operation typically these are written to a http.Request
*/
type AddBodyFatLogParams struct {

	/*Date
	  Log entry date in the format yyyy-MM-dd.

	*/
	Date strfmt.Date
	/*Fat
	  Body fat in the format of X.XX in the unit system that corresponds to the Accept-Language header provided.

	*/
	Fat int64
	/*Time
	  Time of the measurement in hours and minutes in the format HH:mm:ss that is set to the last second of the day if not provided.

	*/
	Time string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add body fat log params
func (o *AddBodyFatLogParams) WithTimeout(timeout time.Duration) *AddBodyFatLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add body fat log params
func (o *AddBodyFatLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add body fat log params
func (o *AddBodyFatLogParams) WithContext(ctx context.Context) *AddBodyFatLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add body fat log params
func (o *AddBodyFatLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add body fat log params
func (o *AddBodyFatLogParams) WithHTTPClient(client *http.Client) *AddBodyFatLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add body fat log params
func (o *AddBodyFatLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDate adds the date to the add body fat log params
func (o *AddBodyFatLogParams) WithDate(date strfmt.Date) *AddBodyFatLogParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the add body fat log params
func (o *AddBodyFatLogParams) SetDate(date strfmt.Date) {
	o.Date = date
}

// WithFat adds the fat to the add body fat log params
func (o *AddBodyFatLogParams) WithFat(fat int64) *AddBodyFatLogParams {
	o.SetFat(fat)
	return o
}

// SetFat adds the fat to the add body fat log params
func (o *AddBodyFatLogParams) SetFat(fat int64) {
	o.Fat = fat
}

// WithTime adds the time to the add body fat log params
func (o *AddBodyFatLogParams) WithTime(time string) *AddBodyFatLogParams {
	o.SetTime(time)
	return o
}

// SetTime adds the time to the add body fat log params
func (o *AddBodyFatLogParams) SetTime(time string) {
	o.Time = time
}

// WriteToRequest writes these params to a swagger request
func (o *AddBodyFatLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param date
	qrDate := o.Date
	qDate := qrDate.String()
	if qDate != "" {
		if err := r.SetQueryParam("date", qDate); err != nil {
			return err
		}
	}

	// query param fat
	qrFat := o.Fat
	qFat := swag.FormatInt64(qrFat)
	if qFat != "" {
		if err := r.SetQueryParam("fat", qFat); err != nil {
			return err
		}
	}

	// query param time
	qrTime := o.Time
	qTime := qrTime
	if qTime != "" {
		if err := r.SetQueryParam("time", qTime); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
