// Code generated by go-swagger; DO NOT EDIT.

package body_and_weight

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetWeightByDatePeriodReader is a Reader for the GetWeightByDatePeriod structure.
type GetWeightByDatePeriodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWeightByDatePeriodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWeightByDatePeriodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetWeightByDatePeriodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetWeightByDatePeriodUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWeightByDatePeriodOK creates a GetWeightByDatePeriodOK with default headers values
func NewGetWeightByDatePeriodOK() *GetWeightByDatePeriodOK {
	return &GetWeightByDatePeriodOK{}
}

/*GetWeightByDatePeriodOK handles this case with default header values.

A successful request.
*/
type GetWeightByDatePeriodOK struct {
}

func (o *GetWeightByDatePeriodOK) Error() string {
	return fmt.Sprintf("[GET /1/user/-/body/log/weight/date/{date}/{period}.json][%d] getWeightByDatePeriodOK ", 200)
}

func (o *GetWeightByDatePeriodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetWeightByDatePeriodBadRequest creates a GetWeightByDatePeriodBadRequest with default headers values
func NewGetWeightByDatePeriodBadRequest() *GetWeightByDatePeriodBadRequest {
	return &GetWeightByDatePeriodBadRequest{}
}

/*GetWeightByDatePeriodBadRequest handles this case with default header values.

The request had bad syntax or was inherently impossible to be satified.
*/
type GetWeightByDatePeriodBadRequest struct {
}

func (o *GetWeightByDatePeriodBadRequest) Error() string {
	return fmt.Sprintf("[GET /1/user/-/body/log/weight/date/{date}/{period}.json][%d] getWeightByDatePeriodBadRequest ", 400)
}

func (o *GetWeightByDatePeriodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetWeightByDatePeriodUnauthorized creates a GetWeightByDatePeriodUnauthorized with default headers values
func NewGetWeightByDatePeriodUnauthorized() *GetWeightByDatePeriodUnauthorized {
	return &GetWeightByDatePeriodUnauthorized{}
}

/*GetWeightByDatePeriodUnauthorized handles this case with default header values.

The request requires user authentication.
*/
type GetWeightByDatePeriodUnauthorized struct {
}

func (o *GetWeightByDatePeriodUnauthorized) Error() string {
	return fmt.Sprintf("[GET /1/user/-/body/log/weight/date/{date}/{period}.json][%d] getWeightByDatePeriodUnauthorized ", 401)
}

func (o *GetWeightByDatePeriodUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
