// Code generated by go-swagger; DO NOT EDIT.

package body_and_weight

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBodyFatByDateParams creates a new GetBodyFatByDateParams object
// with the default values initialized.
func NewGetBodyFatByDateParams() *GetBodyFatByDateParams {
	var ()
	return &GetBodyFatByDateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBodyFatByDateParamsWithTimeout creates a new GetBodyFatByDateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBodyFatByDateParamsWithTimeout(timeout time.Duration) *GetBodyFatByDateParams {
	var ()
	return &GetBodyFatByDateParams{

		timeout: timeout,
	}
}

// NewGetBodyFatByDateParamsWithContext creates a new GetBodyFatByDateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBodyFatByDateParamsWithContext(ctx context.Context) *GetBodyFatByDateParams {
	var ()
	return &GetBodyFatByDateParams{

		Context: ctx,
	}
}

// NewGetBodyFatByDateParamsWithHTTPClient creates a new GetBodyFatByDateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBodyFatByDateParamsWithHTTPClient(client *http.Client) *GetBodyFatByDateParams {
	var ()
	return &GetBodyFatByDateParams{
		HTTPClient: client,
	}
}

/*GetBodyFatByDateParams contains all the parameters to send to the API endpoint
for the get body fat by date operation typically these are written to a http.Request
*/
type GetBodyFatByDateParams struct {

	/*Date
	  The date in the format yyyy-MM-dd.

	*/
	Date strfmt.Date

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get body fat by date params
func (o *GetBodyFatByDateParams) WithTimeout(timeout time.Duration) *GetBodyFatByDateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get body fat by date params
func (o *GetBodyFatByDateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get body fat by date params
func (o *GetBodyFatByDateParams) WithContext(ctx context.Context) *GetBodyFatByDateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get body fat by date params
func (o *GetBodyFatByDateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get body fat by date params
func (o *GetBodyFatByDateParams) WithHTTPClient(client *http.Client) *GetBodyFatByDateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get body fat by date params
func (o *GetBodyFatByDateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDate adds the date to the get body fat by date params
func (o *GetBodyFatByDateParams) WithDate(date strfmt.Date) *GetBodyFatByDateParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the get body fat by date params
func (o *GetBodyFatByDateParams) SetDate(date strfmt.Date) {
	o.Date = date
}

// WriteToRequest writes these params to a swagger request
func (o *GetBodyFatByDateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param date
	if err := r.SetPathParam("date", o.Date.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
