// Code generated by go-swagger; DO NOT EDIT.

package body_and_weight

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBodyGoalsParams creates a new GetBodyGoalsParams object
// with the default values initialized.
func NewGetBodyGoalsParams() *GetBodyGoalsParams {
	var ()
	return &GetBodyGoalsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBodyGoalsParamsWithTimeout creates a new GetBodyGoalsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBodyGoalsParamsWithTimeout(timeout time.Duration) *GetBodyGoalsParams {
	var ()
	return &GetBodyGoalsParams{

		timeout: timeout,
	}
}

// NewGetBodyGoalsParamsWithContext creates a new GetBodyGoalsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBodyGoalsParamsWithContext(ctx context.Context) *GetBodyGoalsParams {
	var ()
	return &GetBodyGoalsParams{

		Context: ctx,
	}
}

// NewGetBodyGoalsParamsWithHTTPClient creates a new GetBodyGoalsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBodyGoalsParamsWithHTTPClient(client *http.Client) *GetBodyGoalsParams {
	var ()
	return &GetBodyGoalsParams{
		HTTPClient: client,
	}
}

/*GetBodyGoalsParams contains all the parameters to send to the API endpoint
for the get body goals operation typically these are written to a http.Request
*/
type GetBodyGoalsParams struct {

	/*GoalType
	  weight or fat.

	*/
	GoalType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get body goals params
func (o *GetBodyGoalsParams) WithTimeout(timeout time.Duration) *GetBodyGoalsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get body goals params
func (o *GetBodyGoalsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get body goals params
func (o *GetBodyGoalsParams) WithContext(ctx context.Context) *GetBodyGoalsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get body goals params
func (o *GetBodyGoalsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get body goals params
func (o *GetBodyGoalsParams) WithHTTPClient(client *http.Client) *GetBodyGoalsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get body goals params
func (o *GetBodyGoalsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGoalType adds the goalType to the get body goals params
func (o *GetBodyGoalsParams) WithGoalType(goalType string) *GetBodyGoalsParams {
	o.SetGoalType(goalType)
	return o
}

// SetGoalType adds the goalType to the get body goals params
func (o *GetBodyGoalsParams) SetGoalType(goalType string) {
	o.GoalType = goalType
}

// WriteToRequest writes these params to a swagger request
func (o *GetBodyGoalsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param goal-type
	if err := r.SetPathParam("goal-type", o.GoalType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
