// Code generated by go-swagger; DO NOT EDIT.

package body_and_weight

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWeightByDatePeriodParams creates a new GetWeightByDatePeriodParams object
// with the default values initialized.
func NewGetWeightByDatePeriodParams() *GetWeightByDatePeriodParams {
	var ()
	return &GetWeightByDatePeriodParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWeightByDatePeriodParamsWithTimeout creates a new GetWeightByDatePeriodParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWeightByDatePeriodParamsWithTimeout(timeout time.Duration) *GetWeightByDatePeriodParams {
	var ()
	return &GetWeightByDatePeriodParams{

		timeout: timeout,
	}
}

// NewGetWeightByDatePeriodParamsWithContext creates a new GetWeightByDatePeriodParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWeightByDatePeriodParamsWithContext(ctx context.Context) *GetWeightByDatePeriodParams {
	var ()
	return &GetWeightByDatePeriodParams{

		Context: ctx,
	}
}

// NewGetWeightByDatePeriodParamsWithHTTPClient creates a new GetWeightByDatePeriodParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWeightByDatePeriodParamsWithHTTPClient(client *http.Client) *GetWeightByDatePeriodParams {
	var ()
	return &GetWeightByDatePeriodParams{
		HTTPClient: client,
	}
}

/*GetWeightByDatePeriodParams contains all the parameters to send to the API endpoint
for the get weight by date period operation typically these are written to a http.Request
*/
type GetWeightByDatePeriodParams struct {

	/*Date
	  The date in the format yyyy-MM-dd.

	*/
	Date strfmt.Date
	/*Period
	  The range for which data will be returned. Options are 1d, 7d, 30d, 1w, 1m, 3m, 6m, 1y, or max.

	*/
	Period string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get weight by date period params
func (o *GetWeightByDatePeriodParams) WithTimeout(timeout time.Duration) *GetWeightByDatePeriodParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get weight by date period params
func (o *GetWeightByDatePeriodParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get weight by date period params
func (o *GetWeightByDatePeriodParams) WithContext(ctx context.Context) *GetWeightByDatePeriodParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get weight by date period params
func (o *GetWeightByDatePeriodParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get weight by date period params
func (o *GetWeightByDatePeriodParams) WithHTTPClient(client *http.Client) *GetWeightByDatePeriodParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get weight by date period params
func (o *GetWeightByDatePeriodParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDate adds the date to the get weight by date period params
func (o *GetWeightByDatePeriodParams) WithDate(date strfmt.Date) *GetWeightByDatePeriodParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the get weight by date period params
func (o *GetWeightByDatePeriodParams) SetDate(date strfmt.Date) {
	o.Date = date
}

// WithPeriod adds the period to the get weight by date period params
func (o *GetWeightByDatePeriodParams) WithPeriod(period string) *GetWeightByDatePeriodParams {
	o.SetPeriod(period)
	return o
}

// SetPeriod adds the period to the get weight by date period params
func (o *GetWeightByDatePeriodParams) SetPeriod(period string) {
	o.Period = period
}

// WriteToRequest writes these params to a swagger request
func (o *GetWeightByDatePeriodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param date
	if err := r.SetPathParam("date", o.Date.String()); err != nil {
		return err
	}

	// path param period
	if err := r.SetPathParam("period", o.Period); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
