// Code generated by go-swagger; DO NOT EDIT.

package body_and_weight

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBodyFatByDateRangeParams creates a new GetBodyFatByDateRangeParams object
// with the default values initialized.
func NewGetBodyFatByDateRangeParams() *GetBodyFatByDateRangeParams {
	var ()
	return &GetBodyFatByDateRangeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBodyFatByDateRangeParamsWithTimeout creates a new GetBodyFatByDateRangeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBodyFatByDateRangeParamsWithTimeout(timeout time.Duration) *GetBodyFatByDateRangeParams {
	var ()
	return &GetBodyFatByDateRangeParams{

		timeout: timeout,
	}
}

// NewGetBodyFatByDateRangeParamsWithContext creates a new GetBodyFatByDateRangeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBodyFatByDateRangeParamsWithContext(ctx context.Context) *GetBodyFatByDateRangeParams {
	var ()
	return &GetBodyFatByDateRangeParams{

		Context: ctx,
	}
}

// NewGetBodyFatByDateRangeParamsWithHTTPClient creates a new GetBodyFatByDateRangeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBodyFatByDateRangeParamsWithHTTPClient(client *http.Client) *GetBodyFatByDateRangeParams {
	var ()
	return &GetBodyFatByDateRangeParams{
		HTTPClient: client,
	}
}

/*GetBodyFatByDateRangeParams contains all the parameters to send to the API endpoint
for the get body fat by date range operation typically these are written to a http.Request
*/
type GetBodyFatByDateRangeParams struct {

	/*BaseDate
	  The range start date in the format yyyy-MM-dd or today.

	*/
	BaseDate strfmt.Date
	/*EndDate
	  The end date of the range.

	*/
	EndDate strfmt.Date

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get body fat by date range params
func (o *GetBodyFatByDateRangeParams) WithTimeout(timeout time.Duration) *GetBodyFatByDateRangeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get body fat by date range params
func (o *GetBodyFatByDateRangeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get body fat by date range params
func (o *GetBodyFatByDateRangeParams) WithContext(ctx context.Context) *GetBodyFatByDateRangeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get body fat by date range params
func (o *GetBodyFatByDateRangeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get body fat by date range params
func (o *GetBodyFatByDateRangeParams) WithHTTPClient(client *http.Client) *GetBodyFatByDateRangeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get body fat by date range params
func (o *GetBodyFatByDateRangeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseDate adds the baseDate to the get body fat by date range params
func (o *GetBodyFatByDateRangeParams) WithBaseDate(baseDate strfmt.Date) *GetBodyFatByDateRangeParams {
	o.SetBaseDate(baseDate)
	return o
}

// SetBaseDate adds the baseDate to the get body fat by date range params
func (o *GetBodyFatByDateRangeParams) SetBaseDate(baseDate strfmt.Date) {
	o.BaseDate = baseDate
}

// WithEndDate adds the endDate to the get body fat by date range params
func (o *GetBodyFatByDateRangeParams) WithEndDate(endDate strfmt.Date) *GetBodyFatByDateRangeParams {
	o.SetEndDate(endDate)
	return o
}

// SetEndDate adds the endDate to the get body fat by date range params
func (o *GetBodyFatByDateRangeParams) SetEndDate(endDate strfmt.Date) {
	o.EndDate = endDate
}

// WriteToRequest writes these params to a swagger request
func (o *GetBodyFatByDateRangeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param base-date
	if err := r.SetPathParam("base-date", o.BaseDate.String()); err != nil {
		return err
	}

	// path param end-date
	if err := r.SetPathParam("end-date", o.EndDate.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
