// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// IntrospectReader is a Reader for the Introspect structure.
type IntrospectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IntrospectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIntrospectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewIntrospectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewIntrospectUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewIntrospectConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIntrospectOK creates a IntrospectOK with default headers values
func NewIntrospectOK() *IntrospectOK {
	return &IntrospectOK{}
}

/*IntrospectOK handles this case with default header values.

A successful request.
*/
type IntrospectOK struct {
}

func (o *IntrospectOK) Error() string {
	return fmt.Sprintf("[POST /1.1/oauth2/introspect][%d] introspectOK ", 200)
}

func (o *IntrospectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewIntrospectBadRequest creates a IntrospectBadRequest with default headers values
func NewIntrospectBadRequest() *IntrospectBadRequest {
	return &IntrospectBadRequest{}
}

/*IntrospectBadRequest handles this case with default header values.

The request had bad syntax or was inherently impossible to be satisfied.
*/
type IntrospectBadRequest struct {
}

func (o *IntrospectBadRequest) Error() string {
	return fmt.Sprintf("[POST /1.1/oauth2/introspect][%d] introspectBadRequest ", 400)
}

func (o *IntrospectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewIntrospectUnauthorized creates a IntrospectUnauthorized with default headers values
func NewIntrospectUnauthorized() *IntrospectUnauthorized {
	return &IntrospectUnauthorized{}
}

/*IntrospectUnauthorized handles this case with default header values.

Authentication was unsuccessful due to invalid client credentials.
*/
type IntrospectUnauthorized struct {
}

func (o *IntrospectUnauthorized) Error() string {
	return fmt.Sprintf("[POST /1.1/oauth2/introspect][%d] introspectUnauthorized ", 401)
}

func (o *IntrospectUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewIntrospectConflict creates a IntrospectConflict with default headers values
func NewIntrospectConflict() *IntrospectConflict {
	return &IntrospectConflict{}
}

/*IntrospectConflict handles this case with default header values.

Request conflict due to multiple clients
*/
type IntrospectConflict struct {
}

func (o *IntrospectConflict) Error() string {
	return fmt.Sprintf("[POST /1.1/oauth2/introspect][%d] introspectConflict ", 409)
}

func (o *IntrospectConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
