// Code generated by go-swagger; DO NOT EDIT.

package food_logging

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAddMealParams creates a new AddMealParams object
// with the default values initialized.
func NewAddMealParams() *AddMealParams {
	var ()
	return &AddMealParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddMealParamsWithTimeout creates a new AddMealParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddMealParamsWithTimeout(timeout time.Duration) *AddMealParams {
	var ()
	return &AddMealParams{

		timeout: timeout,
	}
}

// NewAddMealParamsWithContext creates a new AddMealParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddMealParamsWithContext(ctx context.Context) *AddMealParams {
	var ()
	return &AddMealParams{

		Context: ctx,
	}
}

// NewAddMealParamsWithHTTPClient creates a new AddMealParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddMealParamsWithHTTPClient(client *http.Client) *AddMealParams {
	var ()
	return &AddMealParams{
		HTTPClient: client,
	}
}

/*AddMealParams contains all the parameters to send to the API endpoint
for the add meal operation typically these are written to a http.Request
*/
type AddMealParams struct {

	/*Description
	  Short description of the meal.

	*/
	Description string
	/*Amount
	  Amount consumed; in the format X.XX, in the specified unitId.

	*/
	Amount string
	/*FoodID
	  ID of the food to be included in the meal.

	*/
	FoodID string
	/*Name
	  Name of the meal.

	*/
	Name string
	/*UnitID
	  ID of units used. Typically retrieved via a previous call to Get Food Logs, Search Foods, or Get Food Units.

	*/
	UnitID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add meal params
func (o *AddMealParams) WithTimeout(timeout time.Duration) *AddMealParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add meal params
func (o *AddMealParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add meal params
func (o *AddMealParams) WithContext(ctx context.Context) *AddMealParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add meal params
func (o *AddMealParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add meal params
func (o *AddMealParams) WithHTTPClient(client *http.Client) *AddMealParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add meal params
func (o *AddMealParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescription adds the description to the add meal params
func (o *AddMealParams) WithDescription(description string) *AddMealParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the add meal params
func (o *AddMealParams) SetDescription(description string) {
	o.Description = description
}

// WithAmount adds the amount to the add meal params
func (o *AddMealParams) WithAmount(amount string) *AddMealParams {
	o.SetAmount(amount)
	return o
}

// SetAmount adds the amount to the add meal params
func (o *AddMealParams) SetAmount(amount string) {
	o.Amount = amount
}

// WithFoodID adds the foodID to the add meal params
func (o *AddMealParams) WithFoodID(foodID string) *AddMealParams {
	o.SetFoodID(foodID)
	return o
}

// SetFoodID adds the foodId to the add meal params
func (o *AddMealParams) SetFoodID(foodID string) {
	o.FoodID = foodID
}

// WithName adds the name to the add meal params
func (o *AddMealParams) WithName(name string) *AddMealParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the add meal params
func (o *AddMealParams) SetName(name string) {
	o.Name = name
}

// WithUnitID adds the unitID to the add meal params
func (o *AddMealParams) WithUnitID(unitID string) *AddMealParams {
	o.SetUnitID(unitID)
	return o
}

// SetUnitID adds the unitId to the add meal params
func (o *AddMealParams) SetUnitID(unitID string) {
	o.UnitID = unitID
}

// WriteToRequest writes these params to a swagger request
func (o *AddMealParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param Description
	qrDescription := o.Description
	qDescription := qrDescription
	if qDescription != "" {
		if err := r.SetQueryParam("Description", qDescription); err != nil {
			return err
		}
	}

	// query param amount
	qrAmount := o.Amount
	qAmount := qrAmount
	if qAmount != "" {
		if err := r.SetQueryParam("amount", qAmount); err != nil {
			return err
		}
	}

	// query param foodId
	qrFoodID := o.FoodID
	qFoodID := qrFoodID
	if qFoodID != "" {
		if err := r.SetQueryParam("foodId", qFoodID); err != nil {
			return err
		}
	}

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {
		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	// query param unitId
	qrUnitID := o.UnitID
	qUnitID := qrUnitID
	if qUnitID != "" {
		if err := r.SetQueryParam("unitId", qUnitID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
