// Code generated by go-swagger; DO NOT EDIT.

package food_logging

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteFavoriteFoodReader is a Reader for the DeleteFavoriteFood structure.
type DeleteFavoriteFoodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFavoriteFoodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteFavoriteFoodNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteFavoriteFoodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteFavoriteFoodUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteFavoriteFoodForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteFavoriteFoodNoContent creates a DeleteFavoriteFoodNoContent with default headers values
func NewDeleteFavoriteFoodNoContent() *DeleteFavoriteFoodNoContent {
	return &DeleteFavoriteFoodNoContent{}
}

/*DeleteFavoriteFoodNoContent handles this case with default header values.

successful request
*/
type DeleteFavoriteFoodNoContent struct {
}

func (o *DeleteFavoriteFoodNoContent) Error() string {
	return fmt.Sprintf("[DELETE /1/user/-/foods/log/favorite/{food-id}.json][%d] deleteFavoriteFoodNoContent ", 204)
}

func (o *DeleteFavoriteFoodNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFavoriteFoodBadRequest creates a DeleteFavoriteFoodBadRequest with default headers values
func NewDeleteFavoriteFoodBadRequest() *DeleteFavoriteFoodBadRequest {
	return &DeleteFavoriteFoodBadRequest{}
}

/*DeleteFavoriteFoodBadRequest handles this case with default header values.

The request had bad syntax or was inherently impossible to be satified.
*/
type DeleteFavoriteFoodBadRequest struct {
}

func (o *DeleteFavoriteFoodBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /1/user/-/foods/log/favorite/{food-id}.json][%d] deleteFavoriteFoodBadRequest ", 400)
}

func (o *DeleteFavoriteFoodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFavoriteFoodUnauthorized creates a DeleteFavoriteFoodUnauthorized with default headers values
func NewDeleteFavoriteFoodUnauthorized() *DeleteFavoriteFoodUnauthorized {
	return &DeleteFavoriteFoodUnauthorized{}
}

/*DeleteFavoriteFoodUnauthorized handles this case with default header values.

The request requires user authentication.
*/
type DeleteFavoriteFoodUnauthorized struct {
}

func (o *DeleteFavoriteFoodUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /1/user/-/foods/log/favorite/{food-id}.json][%d] deleteFavoriteFoodUnauthorized ", 401)
}

func (o *DeleteFavoriteFoodUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFavoriteFoodForbidden creates a DeleteFavoriteFoodForbidden with default headers values
func NewDeleteFavoriteFoodForbidden() *DeleteFavoriteFoodForbidden {
	return &DeleteFavoriteFoodForbidden{}
}

/*DeleteFavoriteFoodForbidden handles this case with default header values.

The server understood the request, but is refusing to fulfill it.
*/
type DeleteFavoriteFoodForbidden struct {
}

func (o *DeleteFavoriteFoodForbidden) Error() string {
	return fmt.Sprintf("[DELETE /1/user/-/foods/log/favorite/{food-id}.json][%d] deleteFavoriteFoodForbidden ", 403)
}

func (o *DeleteFavoriteFoodForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
