// Code generated by go-swagger; DO NOT EDIT.

package food_logging

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteWaterLogParams creates a new DeleteWaterLogParams object
// with the default values initialized.
func NewDeleteWaterLogParams() *DeleteWaterLogParams {
	var ()
	return &DeleteWaterLogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteWaterLogParamsWithTimeout creates a new DeleteWaterLogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteWaterLogParamsWithTimeout(timeout time.Duration) *DeleteWaterLogParams {
	var ()
	return &DeleteWaterLogParams{

		timeout: timeout,
	}
}

// NewDeleteWaterLogParamsWithContext creates a new DeleteWaterLogParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteWaterLogParamsWithContext(ctx context.Context) *DeleteWaterLogParams {
	var ()
	return &DeleteWaterLogParams{

		Context: ctx,
	}
}

// NewDeleteWaterLogParamsWithHTTPClient creates a new DeleteWaterLogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteWaterLogParamsWithHTTPClient(client *http.Client) *DeleteWaterLogParams {
	var ()
	return &DeleteWaterLogParams{
		HTTPClient: client,
	}
}

/*DeleteWaterLogParams contains all the parameters to send to the API endpoint
for the delete water log operation typically these are written to a http.Request
*/
type DeleteWaterLogParams struct {

	/*WaterLogID
	  The ID of the waterUnit log entry to be deleted.

	*/
	WaterLogID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete water log params
func (o *DeleteWaterLogParams) WithTimeout(timeout time.Duration) *DeleteWaterLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete water log params
func (o *DeleteWaterLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete water log params
func (o *DeleteWaterLogParams) WithContext(ctx context.Context) *DeleteWaterLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete water log params
func (o *DeleteWaterLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete water log params
func (o *DeleteWaterLogParams) WithHTTPClient(client *http.Client) *DeleteWaterLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete water log params
func (o *DeleteWaterLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWaterLogID adds the waterLogID to the delete water log params
func (o *DeleteWaterLogParams) WithWaterLogID(waterLogID string) *DeleteWaterLogParams {
	o.SetWaterLogID(waterLogID)
	return o
}

// SetWaterLogID adds the waterLogId to the delete water log params
func (o *DeleteWaterLogParams) SetWaterLogID(waterLogID string) {
	o.WaterLogID = waterLogID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteWaterLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param water-log-id
	if err := r.SetPathParam("water-log-id", o.WaterLogID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
