// Code generated by go-swagger; DO NOT EDIT.

package food_logging

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFavoriteFoodsParams creates a new GetFavoriteFoodsParams object
// with the default values initialized.
func NewGetFavoriteFoodsParams() *GetFavoriteFoodsParams {

	return &GetFavoriteFoodsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFavoriteFoodsParamsWithTimeout creates a new GetFavoriteFoodsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFavoriteFoodsParamsWithTimeout(timeout time.Duration) *GetFavoriteFoodsParams {

	return &GetFavoriteFoodsParams{

		timeout: timeout,
	}
}

// NewGetFavoriteFoodsParamsWithContext creates a new GetFavoriteFoodsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFavoriteFoodsParamsWithContext(ctx context.Context) *GetFavoriteFoodsParams {

	return &GetFavoriteFoodsParams{

		Context: ctx,
	}
}

// NewGetFavoriteFoodsParamsWithHTTPClient creates a new GetFavoriteFoodsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFavoriteFoodsParamsWithHTTPClient(client *http.Client) *GetFavoriteFoodsParams {

	return &GetFavoriteFoodsParams{
		HTTPClient: client,
	}
}

/*GetFavoriteFoodsParams contains all the parameters to send to the API endpoint
for the get favorite foods operation typically these are written to a http.Request
*/
type GetFavoriteFoodsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get favorite foods params
func (o *GetFavoriteFoodsParams) WithTimeout(timeout time.Duration) *GetFavoriteFoodsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get favorite foods params
func (o *GetFavoriteFoodsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get favorite foods params
func (o *GetFavoriteFoodsParams) WithContext(ctx context.Context) *GetFavoriteFoodsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get favorite foods params
func (o *GetFavoriteFoodsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get favorite foods params
func (o *GetFavoriteFoodsParams) WithHTTPClient(client *http.Client) *GetFavoriteFoodsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get favorite foods params
func (o *GetFavoriteFoodsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetFavoriteFoodsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
