// Code generated by go-swagger; DO NOT EDIT.

package food_logging

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRecentFoodsParams creates a new GetRecentFoodsParams object
// with the default values initialized.
func NewGetRecentFoodsParams() *GetRecentFoodsParams {

	return &GetRecentFoodsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRecentFoodsParamsWithTimeout creates a new GetRecentFoodsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRecentFoodsParamsWithTimeout(timeout time.Duration) *GetRecentFoodsParams {

	return &GetRecentFoodsParams{

		timeout: timeout,
	}
}

// NewGetRecentFoodsParamsWithContext creates a new GetRecentFoodsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRecentFoodsParamsWithContext(ctx context.Context) *GetRecentFoodsParams {

	return &GetRecentFoodsParams{

		Context: ctx,
	}
}

// NewGetRecentFoodsParamsWithHTTPClient creates a new GetRecentFoodsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRecentFoodsParamsWithHTTPClient(client *http.Client) *GetRecentFoodsParams {

	return &GetRecentFoodsParams{
		HTTPClient: client,
	}
}

/*GetRecentFoodsParams contains all the parameters to send to the API endpoint
for the get recent foods operation typically these are written to a http.Request
*/
type GetRecentFoodsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get recent foods params
func (o *GetRecentFoodsParams) WithTimeout(timeout time.Duration) *GetRecentFoodsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get recent foods params
func (o *GetRecentFoodsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get recent foods params
func (o *GetRecentFoodsParams) WithContext(ctx context.Context) *GetRecentFoodsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get recent foods params
func (o *GetRecentFoodsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get recent foods params
func (o *GetRecentFoodsParams) WithHTTPClient(client *http.Client) *GetRecentFoodsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get recent foods params
func (o *GetRecentFoodsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRecentFoodsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
