// Code generated by go-swagger; DO NOT EDIT.

package sleep

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteSleepReader is a Reader for the DeleteSleep structure.
type DeleteSleepReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSleepReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteSleepOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteSleepUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteSleepForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSleepOK creates a DeleteSleepOK with default headers values
func NewDeleteSleepOK() *DeleteSleepOK {
	return &DeleteSleepOK{}
}

/*DeleteSleepOK handles this case with default header values.

Successful request.
*/
type DeleteSleepOK struct {
}

func (o *DeleteSleepOK) Error() string {
	return fmt.Sprintf("[DELETE /1.2/user/-/sleep/{log-id}.json][%d] deleteSleepOK ", 200)
}

func (o *DeleteSleepOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSleepUnauthorized creates a DeleteSleepUnauthorized with default headers values
func NewDeleteSleepUnauthorized() *DeleteSleepUnauthorized {
	return &DeleteSleepUnauthorized{}
}

/*DeleteSleepUnauthorized handles this case with default header values.

The request requires user authentication.
*/
type DeleteSleepUnauthorized struct {
}

func (o *DeleteSleepUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /1.2/user/-/sleep/{log-id}.json][%d] deleteSleepUnauthorized ", 401)
}

func (o *DeleteSleepUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSleepForbidden creates a DeleteSleepForbidden with default headers values
func NewDeleteSleepForbidden() *DeleteSleepForbidden {
	return &DeleteSleepForbidden{}
}

/*DeleteSleepForbidden handles this case with default header values.

The server understood the request, but is refusing to fulfill it.
*/
type DeleteSleepForbidden struct {
}

func (o *DeleteSleepForbidden) Error() string {
	return fmt.Sprintf("[DELETE /1.2/user/-/sleep/{log-id}.json][%d] deleteSleepForbidden ", 403)
}

func (o *DeleteSleepForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
