// Code generated by go-swagger; DO NOT EDIT.

package sleep

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSleepParams creates a new DeleteSleepParams object
// with the default values initialized.
func NewDeleteSleepParams() *DeleteSleepParams {
	var ()
	return &DeleteSleepParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSleepParamsWithTimeout creates a new DeleteSleepParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSleepParamsWithTimeout(timeout time.Duration) *DeleteSleepParams {
	var ()
	return &DeleteSleepParams{

		timeout: timeout,
	}
}

// NewDeleteSleepParamsWithContext creates a new DeleteSleepParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSleepParamsWithContext(ctx context.Context) *DeleteSleepParams {
	var ()
	return &DeleteSleepParams{

		Context: ctx,
	}
}

// NewDeleteSleepParamsWithHTTPClient creates a new DeleteSleepParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSleepParamsWithHTTPClient(client *http.Client) *DeleteSleepParams {
	var ()
	return &DeleteSleepParams{
		HTTPClient: client,
	}
}

/*DeleteSleepParams contains all the parameters to send to the API endpoint
for the delete sleep operation typically these are written to a http.Request
*/
type DeleteSleepParams struct {

	/*LogID
	  The ID of the sleep log to be deleted.

	*/
	LogID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete sleep params
func (o *DeleteSleepParams) WithTimeout(timeout time.Duration) *DeleteSleepParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete sleep params
func (o *DeleteSleepParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete sleep params
func (o *DeleteSleepParams) WithContext(ctx context.Context) *DeleteSleepParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete sleep params
func (o *DeleteSleepParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete sleep params
func (o *DeleteSleepParams) WithHTTPClient(client *http.Client) *DeleteSleepParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete sleep params
func (o *DeleteSleepParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLogID adds the logID to the delete sleep params
func (o *DeleteSleepParams) WithLogID(logID string) *DeleteSleepParams {
	o.SetLogID(logID)
	return o
}

// SetLogID adds the logId to the delete sleep params
func (o *DeleteSleepParams) SetLogID(logID string) {
	o.LogID = logID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSleepParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param log-id
	if err := r.SetPathParam("log-id", o.LogID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
