// Code generated by go-swagger; DO NOT EDIT.

package sleep

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSleepListParams creates a new GetSleepListParams object
// with the default values initialized.
func NewGetSleepListParams() *GetSleepListParams {
	var (
		offsetDefault = int64("0")
	)
	return &GetSleepListParams{
		Offset: offsetDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSleepListParamsWithTimeout creates a new GetSleepListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSleepListParamsWithTimeout(timeout time.Duration) *GetSleepListParams {
	var (
		offsetDefault = int64("0")
	)
	return &GetSleepListParams{
		Offset: offsetDefault,

		timeout: timeout,
	}
}

// NewGetSleepListParamsWithContext creates a new GetSleepListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSleepListParamsWithContext(ctx context.Context) *GetSleepListParams {
	var (
		offsetDefault = int64("0")
	)
	return &GetSleepListParams{
		Offset: offsetDefault,

		Context: ctx,
	}
}

// NewGetSleepListParamsWithHTTPClient creates a new GetSleepListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSleepListParamsWithHTTPClient(client *http.Client) *GetSleepListParams {
	var (
		offsetDefault = int64("0")
	)
	return &GetSleepListParams{
		Offset:     offsetDefault,
		HTTPClient: client,
	}
}

/*GetSleepListParams contains all the parameters to send to the API endpoint
for the get sleep list operation typically these are written to a http.Request
*/
type GetSleepListParams struct {

	/*AfterDate
	  The date in the format yyyy-MM-ddTHH:mm:ss.

	*/
	AfterDate *strfmt.Date
	/*BeforeDate
	  The date in the format yyyy-MM-ddTHH:mm:ss. Only yyyy-MM-dd is required. Either beforeDate or afterDate should be specified.

	*/
	BeforeDate *strfmt.Date
	/*Limit
	  The maximum number of entries returned (maximum;100).

	*/
	Limit int64
	/*Offset
	  The offset number of entries.

	*/
	Offset int64
	/*Sort
	  The sort order of entries by date asc (ascending) or desc (descending).

	*/
	Sort string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sleep list params
func (o *GetSleepListParams) WithTimeout(timeout time.Duration) *GetSleepListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sleep list params
func (o *GetSleepListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sleep list params
func (o *GetSleepListParams) WithContext(ctx context.Context) *GetSleepListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sleep list params
func (o *GetSleepListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sleep list params
func (o *GetSleepListParams) WithHTTPClient(client *http.Client) *GetSleepListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sleep list params
func (o *GetSleepListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAfterDate adds the afterDate to the get sleep list params
func (o *GetSleepListParams) WithAfterDate(afterDate *strfmt.Date) *GetSleepListParams {
	o.SetAfterDate(afterDate)
	return o
}

// SetAfterDate adds the afterDate to the get sleep list params
func (o *GetSleepListParams) SetAfterDate(afterDate *strfmt.Date) {
	o.AfterDate = afterDate
}

// WithBeforeDate adds the beforeDate to the get sleep list params
func (o *GetSleepListParams) WithBeforeDate(beforeDate *strfmt.Date) *GetSleepListParams {
	o.SetBeforeDate(beforeDate)
	return o
}

// SetBeforeDate adds the beforeDate to the get sleep list params
func (o *GetSleepListParams) SetBeforeDate(beforeDate *strfmt.Date) {
	o.BeforeDate = beforeDate
}

// WithLimit adds the limit to the get sleep list params
func (o *GetSleepListParams) WithLimit(limit int64) *GetSleepListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get sleep list params
func (o *GetSleepListParams) SetLimit(limit int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get sleep list params
func (o *GetSleepListParams) WithOffset(offset int64) *GetSleepListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get sleep list params
func (o *GetSleepListParams) SetOffset(offset int64) {
	o.Offset = offset
}

// WithSort adds the sort to the get sleep list params
func (o *GetSleepListParams) WithSort(sort string) *GetSleepListParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get sleep list params
func (o *GetSleepListParams) SetSort(sort string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *GetSleepListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AfterDate != nil {

		// query param afterDate
		var qrAfterDate strfmt.Date
		if o.AfterDate != nil {
			qrAfterDate = *o.AfterDate
		}
		qAfterDate := qrAfterDate.String()
		if qAfterDate != "" {
			if err := r.SetQueryParam("afterDate", qAfterDate); err != nil {
				return err
			}
		}

	}

	if o.BeforeDate != nil {

		// query param beforeDate
		var qrBeforeDate strfmt.Date
		if o.BeforeDate != nil {
			qrBeforeDate = *o.BeforeDate
		}
		qBeforeDate := qrBeforeDate.String()
		if qBeforeDate != "" {
			if err := r.SetQueryParam("beforeDate", qBeforeDate); err != nil {
				return err
			}
		}

	}

	// query param limit
	qrLimit := o.Limit
	qLimit := swag.FormatInt64(qrLimit)
	if qLimit != "" {
		if err := r.SetQueryParam("limit", qLimit); err != nil {
			return err
		}
	}

	// query param offset
	qrOffset := o.Offset
	qOffset := swag.FormatInt64(qrOffset)
	if qOffset != "" {
		if err := r.SetQueryParam("offset", qOffset); err != nil {
			return err
		}
	}

	// query param sort
	qrSort := o.Sort
	qSort := qrSort
	if qSort != "" {
		if err := r.SetQueryParam("sort", qSort); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
