// Code generated by go-swagger; DO NOT EDIT.

package sleep

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSleepByDateRangeParams creates a new GetSleepByDateRangeParams object
// with the default values initialized.
func NewGetSleepByDateRangeParams() *GetSleepByDateRangeParams {
	var ()
	return &GetSleepByDateRangeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSleepByDateRangeParamsWithTimeout creates a new GetSleepByDateRangeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSleepByDateRangeParamsWithTimeout(timeout time.Duration) *GetSleepByDateRangeParams {
	var ()
	return &GetSleepByDateRangeParams{

		timeout: timeout,
	}
}

// NewGetSleepByDateRangeParamsWithContext creates a new GetSleepByDateRangeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSleepByDateRangeParamsWithContext(ctx context.Context) *GetSleepByDateRangeParams {
	var ()
	return &GetSleepByDateRangeParams{

		Context: ctx,
	}
}

// NewGetSleepByDateRangeParamsWithHTTPClient creates a new GetSleepByDateRangeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSleepByDateRangeParamsWithHTTPClient(client *http.Client) *GetSleepByDateRangeParams {
	var ()
	return &GetSleepByDateRangeParams{
		HTTPClient: client,
	}
}

/*GetSleepByDateRangeParams contains all the parameters to send to the API endpoint
for the get sleep by date range operation typically these are written to a http.Request
*/
type GetSleepByDateRangeParams struct {

	/*BaseDate
	  The date of records to be returned. In the format yyyy-MM-dd.

	*/
	BaseDate strfmt.Date
	/*EndDate
	  The date of records to be returned. In the format yyyy-MM-dd.

	*/
	EndDate strfmt.Date

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sleep by date range params
func (o *GetSleepByDateRangeParams) WithTimeout(timeout time.Duration) *GetSleepByDateRangeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sleep by date range params
func (o *GetSleepByDateRangeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sleep by date range params
func (o *GetSleepByDateRangeParams) WithContext(ctx context.Context) *GetSleepByDateRangeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sleep by date range params
func (o *GetSleepByDateRangeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sleep by date range params
func (o *GetSleepByDateRangeParams) WithHTTPClient(client *http.Client) *GetSleepByDateRangeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sleep by date range params
func (o *GetSleepByDateRangeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseDate adds the baseDate to the get sleep by date range params
func (o *GetSleepByDateRangeParams) WithBaseDate(baseDate strfmt.Date) *GetSleepByDateRangeParams {
	o.SetBaseDate(baseDate)
	return o
}

// SetBaseDate adds the baseDate to the get sleep by date range params
func (o *GetSleepByDateRangeParams) SetBaseDate(baseDate strfmt.Date) {
	o.BaseDate = baseDate
}

// WithEndDate adds the endDate to the get sleep by date range params
func (o *GetSleepByDateRangeParams) WithEndDate(endDate strfmt.Date) *GetSleepByDateRangeParams {
	o.SetEndDate(endDate)
	return o
}

// SetEndDate adds the endDate to the get sleep by date range params
func (o *GetSleepByDateRangeParams) SetEndDate(endDate strfmt.Date) {
	o.EndDate = endDate
}

// WriteToRequest writes these params to a swagger request
func (o *GetSleepByDateRangeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param base-date
	if err := r.SetPathParam("base-date", o.BaseDate.String()); err != nil {
		return err
	}

	// path param end-date
	if err := r.SetPathParam("end-date", o.EndDate.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
