// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Oauth2Error oauth2 error
// swagger:model Oauth2Error
type Oauth2Error struct {

	// The type of error (see Oauth2 spec).
	ErrorType string `json:"errorType,omitempty"`

	// A detailed description of the error.
	Message string `json:"message,omitempty"`
}

// Validate validates this oauth2 error
func (m *Oauth2Error) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Oauth2Error) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Oauth2Error) UnmarshalBinary(b []byte) error {
	var res Oauth2Error
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
